### ISSUE TITLE
Ditto doesn't send message to a Kafka Topic

### ISSUE THREAD

**Issue by Felice-Copp56** [eclipse-ditto/ditto#1537]
Hi, I'm trying to connect Eclipse Ditto with Apache Kafka in order to send the received messages in a Influxdb's bucket but at moment seems not work.
I have configured a MQTT connection for sending data from an arduino device to ditto and this happens without problem.
Also, I have created a Kafka 2.x connection that returns me a 200 response but the message sends via the MQTT broker doesn't compare on the topic.
This is my connection file
`curl -X POST -i -u devops:foobar  -H 'Content-Type: application/json' -d '{

   "targetActorSelection":"/system/sharding/connection",

   "headers":{

      "aggregate":false

   },

   "piggybackCommand":{

      "type":"connectivity.commands:createConnection",

      "connection":{

         "id":"kafka123",

         "connectionType":"kafka",

         "connectionStatus":"open",

         "failoverEnabled":true,

         "uri":"tcp://192.168.77.74:9092",

         "specificConfig":{

            "bootstrapServers":"192.168.77.74:9092"

         },

         "sources":[

            {

               "addresses":["topic01"],

               "consumerCount":1,

               "qos":0,

               "authorizationContext":["nginx:ditto"],

               "enforcement":{

                  "input":"{{ header:device_id }}",

                  "filters":["{{ entity:id }}"]

               },

               "headerMapping":{

                  "topic01":"{{ header:topic01 }}",

                  "the-key":"{{ header:kafka.key }}"

               },

               "payloadMapping":["Ditto"],

               "replyTarget":{

                  "enabled":true,

                  "address":"topic01",

                  "headerMapping":{

                     

                  },

                  "expectedResponseTypes":[

                     "response",

                     "error",

                     "nack"

                  ]

               },

               "acknowledgementRequests":{

                  "includes":[]

               },

               "declaredAcks":[]

            }

         ]

      }

   }

}' 'http://192.168.77.74:8080/devops/piggyback/connectivity?timeout=10'`

The policy file presents the same authorizationContext = nginx:ditto
Any idea about this problem? I think that Ditto works as a Kafka Producer and with the Kafka 2.x connection send message on the topic but nothing

**Comment by DerSchwilk** [comment]
Hey @Felice-Copp56,
do I get that right, that you want to publish messages/events via your connection?
You configured only a source in your Kafka connection, from which Ditto can consume messages.
In order to also publish messages you need to specify a Kafka target.

https://www.eclipse.org/ditto/connectivity-protocol-bindings-kafka2.html#target-format
https://www.eclipse.org/ditto/basic-connections.html#targets

**Comment by Felice-Copp56** [comment]
Yes, I want to publish message received from a MQTT broker, on a Kafka Topic, is it possible in this way?

**Comment by DerSchwilk** [comment]
Yes, in this case you likely want to publish live-messages which you sent via your MQTT source to Ditto.
You can configure your target to do exactly that: https://www.eclipse.org/ditto/basic-connections.html#target-topics-and-filtering

**Comment by Felice-Copp56** [comment]
I have tried as you said but seems not to work, can I upload my connection config file here? Maybe I type wrong target

**Comment by DerSchwilk** [comment]
Your MQTT connection has no source configured, only a target. Ditto has no way to consume messages from that connection without a source.
You should configure a source accordingly (https://www.eclipse.org/ditto/basic-connections.html#sources) and check your connection logs to whether you're really consuming the messages published by your Arduino device. (https://www.eclipse.org/ditto/connectivity-manage-connections.html#retrieve-connection-logs)

**Comment by Felice-Copp56** [comment]
Sorry, I upload the wrong connection, I have used this type but the same result
`{
    "targetActorSelection": "/system/sharding/connection",
    "headers": {
    	"aggregate": false
    },
    "piggybackCommand": {
        "type": "connectivity.commands:createConnection",
        "connection": {
            "id": "mqtt-connection-source",
            "connectionType": "mqtt",
            "connectionStatus": "open",
            "failoverEnabled": true,
            "uri": "tcp://MY_IP:1883",
            "sources": [{
                "addresses": ["arduino/#"],
                "authorizationContext": ["nginx:ditto"],
                "qos": 0,
                "filters": []
            }],
            "mappingContext": {
                "mappingEngine": "JavaScript",
                "options": {
                    "incomingScript": "function mapToDittoProtocolMsg(headers, textPayload, bytePayload, contentType) {const jsonString = String.fromCharCode.apply(null, new Uint8Array(bytePayload)); const jsonData = JSON.parse(jsonString); const thingId = jsonData.thingId.split(':'); const value = {measurements: {properties: {temperature: jsonData.temperature, humidity: jsonData.humidity}}}; return Ditto.buildDittoProtocolMsg(thingId[0], thingId[1], 'things', 'twin', 'commands', 'modify', '/features', headers, value);}",
                    "outgoingScript": "function mapFromDittoProtocolMsg(namespace, id, group, channel, criterion, action, path, dittoHeaders, value, status, extra) {return null;}",
                    "loadBytebufferJS": "false",
                    "loadLongJS": "false"
                }
            }
        }
    }
}`

**Comment by thjaeckle** [comment]
I would suggest you try (back in my studying time that was part and the idea of studying and self learning) it out before asking the same questions over again via 3 feedback channels.

What you want is (probably, you must know best) an Mqtt connection with a source and a Kafka connection with a target.

If you want to update the twins/things managed in Ditto via Mqtt messages, you can subscribe in the Kafka connection target to twin events and publish those to Kafka.
If you just want to convert Mqtt messages to Kafka messages there are probably easier solutions than to do that via Ditto connections.
