### ISSUE TITLE
Integrating Ditto with GraphDB

### ISSUE THREAD

**Issue by ap0-0rva** [eclipse-ditto/ditto#1562]
Hello

Can we discuss the different possibilities of integrating ditto with GraphDB?
How should one proceed?

**Comment by thjaeckle** [comment]
Hi @ap0-0rva 
Please provide a little more background on your question.

E.g.:
What do you want to solve/achieve with such an integration?
What should be persisted in a Graph database?
Do you want to query the graph database via Ditto APIs?

**Comment by ap0-0rva** [comment]
Hi- sorry about the insufficient information.

**My question aims toward these points: -**
1. Establish connectivity between Eclipse Ditto and Graph DB- modifying the Spring JPA in Ditto source code to work with Neo4J?
2. Any tight coupling existing in the spring data JPA?
3. Updates required to change the data pointers from Mongo DB to any other DB

As of now- we are using MongoDB service as backing datastore of Ditto (and also to get ditto running).
Is it possible to substitute MongoDB with a GraphDB - to store and query the data?

**Comment by thjaeckle** [comment]
I think you have a few misunderstandings.

1. Eclipse Ditto does not make use of Spring or Spring JPA - so there is nothing to modify on that level
2. Same as 1. - there is no Spring Data JPA used .. Ditto makes use of [Akka Persistence](https://doc.akka.io/docs/akka/current/persistence.html) for DB abstraction - as far as I know there is no persistence plugin for neo4j
3. 
   a.) Utilizing the "Akka Persistence" abstraction, switching to another DB should be possible, see the list of [supported plugins](https://doc.akka.io/docs/akka/current/persistence-plugins.html)
   b.) However the Ditto "search" functionality is purely based on MongoDB with no abstraction concept in place - that would require a rewrite to another DB

So substituting MongoDB with another DB could be possible for parts of Ditto (e.g. persistence of things, policies, connections) - but still with quite a few development efforts to replace the custom [MongoReadJournal](https://github.com/eclipse-ditto/ditto/blob/master/internal/utils/persistence/src/main/java/org/eclipse/ditto/internal/utils/persistence/mongo/streaming/MongoReadJournal.java) implementation provided by Ditto.
For other parts like the "search", replacing MongoDB would require a lot of development effort.
