### ISSUE TITLE
Allow setting ca certificate for Hono connection type from configuration file or env variable

### ISSUE THREAD

**Issue by devinsaini** [eclipse-ditto/ditto#1578]
In the new Hono connection type, Kafka connection settings are derived from static config values set from either the config file, or env variables. It will make sense to set the ca certificate from there since it is a part of hono connection configuration. In the current implementation, all Hono/Kafka settings can be set using env vars, but ca has to be specified during connection creation.

It is also a good idea to specify the ca certificate as a path on the file system. This way, we can mount the certificate as a volume and specify its path using an env variable.

Lastly, if there can be a way to sync the ca certificates of all Hono connections on let's say connectivity service restart, then it'll make certificate management much easier. In a production kubernetes setup, if a Hono/Kafka certificate is nearing expiration, the admin will simply have to update the mounted ca secret and restart the connectivity service.

**Comment by thjaeckle** [comment]
That sounds like a good proposal.

@abalarev could you take a look and estimate how much effort that would be?

**Comment by abalarev** [comment]
A new configuration property should be introduced to specify file path of the certificate - tiny effort.

Instead of adding a CA certificate to each connection (that needs one), the service could load the configured certificates in its own new trust store and combine it with the default trust store at service startup.
This seems not a complex task, though sometimes such stuff gets a bit tricky.

**Comment by devinsaini** [comment]
@abalarev You're right, this can be used by connections of any type. Specifying trust stores using a mounted volume will have significant advantages for certificate management. It will then also be possible for production setups to automatically rotate the certificates and update trust store using solutions like cert-manager and trust-manager.

Also, I don't think we need to worry about combining the new trust store with the default trust store. It's usually the responsibility of the cluster admin. For example, trust-manager already allows you to create trust stores that have built-in default CAs.

**Comment by thjaeckle** [comment]
Is there something which has to be done in Ditto @devinsaini @abalarev ?
As far as I understand, the Java truststore location can be configured via environment variable and can be added as a volume/mount to the Ditto connectivity container ..

**Comment by devinsaini** [comment]
@thjaeckle Do you mean using `-Djavax.net.ssl.trustStore=/some/loc/on/server/mytruststore.jks` or is there a Ditto-specific truststore env variable? I will run a test using `-Djavax.net.ssl.trustStore` to see if it works.

**Comment by devinsaini** [comment]
@thjaeckle I tried it and it worked. Thanks for pointing it out.
I'll close the ticket. Thank you.

**Comment by abalarev** [comment]
Thanks @thjaeckle and @devinsaini, nice news for me just coming back from vacation :)
