### ISSUE TITLE
UI: Enhance Ditto-UI to configure log levels of Ditto

### ISSUE THREAD

**Issue by thjaeckle** [eclipse-ditto/ditto#1590]
Ditto provides a "devops" API to retireve and [dynamically adjust log levels](https://www.eclipse.org/ditto/installation-operating.html#dynamically-adjust-log-levels) on the fly without restating Ditto.

This is an extremely helpful thing for admins/operators of Ditto to analyze problems in production.

I suggest to provide a new UI functionality to configure the log levels, in a new "Admin" menu item.
The credentials are the same as for managing connections, so authentication is already handled by the UI.

@thfries what do you think? Other "Admin functionality", eg bypassing policies for accessing the manged things, policies could also be added in the future.

**Comment by thfries** [comment]
Sure, sounds not too complicated. I'm not used to these use cases but I can try to make a proposal.

**Comment by thfries** [comment]
I'm working on that
