### ISSUE TITLE
Change notification filtering doesn't work for desired properties changes

### ISSUE THREAD

**Issue by kyberpunk** [eclipse-ditto/ditto#1599]
Hello. I'm trying to setup Kafka connection with target using following topic filter: `_/_/things/twin/events?extraFields=features/{{feature:id}}&filter=like(resource:path,'/features/RemoteAccessConnections*')`. It works ok for feature change events by changing whole RemoteAccessConnections feature on the thing. But no changes of desired properties are propagated to Kafka (e.g. by `PUT /api/2/things/test:device/features/RemoteAccessConnections/desiredProperties`). 

I did some debugging and came to conclusion that problem is in class [ThingEventToThingConverter](https://github.com/eclipse-ditto/ditto/blob/master/things/model/src/main/java/org/eclipse/ditto/things/model/signals/events/ThingEventToThingConverter.java#L111) because there is no mapping for FeatureDesiredPropertiesModified (an other) event defined and as a consequence signal filtering fails in this [method](https://github.com/eclipse-ditto/ditto/blob/master/connectivity/service/src/main/java/org/eclipse/ditto/connectivity/service/messaging/persistence/SignalFilter.java#L178) for such events.

Am I doing something wrong or is it intended behavior? In this [article ](https://www.eclipse.org/ditto/2020-11-11-desired-properties.html) it is explicitly said that enrichment and filtering should be supported also for desired properties so I would consider it as a bug.

If it is a bug I would be happy to help with solving the issue.

**Comment by thjaeckle** [comment]
Hello @kyberpunk
Thank you for this excellent issue description and digging into the code.

Like you concluded correctly, this sounds also like a bug to me, as the mapping in the code you pointed out is missing.
Apparently also no unit test case covers this. :/

It would be great and much appreciated if you could provide a fix, even more awesome if a unit test could cover this.

Looking forward..
