### ISSUE TITLE
payload mapper failed for ditto-example/mqtt-bidirectional 

### ISSUE THREAD

**Issue by thebist1234** [eclipse-ditto/ditto#1612]
Hi, Hope you are doing Great.
I am new with ditto and need help.
I used docker compose method to run ditto and connect it to mqtt.
I tried [this example](https://github.com/eclipse-ditto/ditto-examples/tree/master/mqtt-bidirectional) and in case of mapper I got this error while I'm receiving messages from my device in logs:
``` 
{
  "correlationId": "<not-provided>",
  "timestamp": "2023-04-10T08:40:49.162739610Z",
  "category": "source",
  "type": "mapped",
  "level": "failure",
  "message": "Got exception <json.field.missing> when processing external message with mapper <default>: JSON did not include required </topic> field! - Message headers: [mqtt.qos=0, mqtt.retain=false, mqtt.topic=/test/fan01] - Message payload: {\"thingId\": \"fan:octopus\", \"Value\": 0}",
  "address": "/test/#"
} 
```
How I created my thing:
```
curl -X PUT 'http://localhost:8080/api/2/things/fan:octopus' -u 'ditto:ditto' -H 'Content-Type: application/json' -d '{
    "policyId": "fan:policy",
    "attributes": {
        "name": "octopus",
        "type": "octopus board"
    },
    "features": {
        "fan": {
            "properties": {
                "value": 0
            }
        }
    }
}'


```
How I configure connection:
```
curl -X POST 'http://localhost:8080/devops/piggyback/connectivity?' -u 'devops:foobar' -H 'Content-Type: application/json' -d '{
    "targetActorSelection": "/system/sharding/connection",
    "headers": {
    	"aggregate": false
    },
    "piggybackCommand": {
        "type": "connectivity.commands:createConnection",
        "connection": {
            "name":"reza",
            "id": "reza",
            "connectionType": "mqtt",
            "connectionStatus": "open",
            "failoverEnabled": true,
            "uri": "tcp://mqtt:1883",
            "sources": [{
                "addresses": ["/test/#"],
                "authorizationContext": ["nginx:ditto"],
                "qos": 0,
                "filters": []
            }],
            "targets": [{
                "address": "/test/fan01",
                "topics": [
                "_/_/things/twin/events",
                "_/_/things/live/messages"
             
                ],
                "authorizationContext": ["nginx:ditto"],
                "qos": 0
            }]
        }
    }
}'

```
The function I'm using for mapping:

```
function mapToDittoProtocolMsg(headers, textPayload, bytePayload, contentType) {
    const jsonString = String.fromCharCode.apply(null, new Uint8Array(textPayload));
    const jsonData = JSON.parse(jsonString); 
    const thingId = jsonData.thingId.split(':'); 
    const value = { 
        fan: { 
            properties: { 
                value: jsonData.Value 
            } 
        }   
    };    
    return Ditto.buildDittoProtocolMsg(
        thingId[0], // your namespace 
        thingId[1], 
        'things', // we deal with a thing
        'twin', // we want to update the twin
        'commands', // create a command to update the twin
        'modify', // modify the twin
        '/features', // modify all features at once
        headers, 
        value
    );
}

```
How I send message:(using python paho mqtt )
```
publish.single( "/test/fan01" , json.dumps({"thingId":"fan:octopus","Value" : random.choice(fan)}), qos=2, retain=False, hostname=url,
            port=Mqtt_port, client_id="fan01", keepalive=60)

```
It means I'm sending this as JSON:
```
{"thingId": "fan:octopus", "Value": 1}

```
I Received All messages and I can see them in logs but mapper does not work. also I set mapper using Ui as you can see it here:
[Image](https://ibb.co/TMCqTV7)
so what is this error for??
@thjaeckle 
can you help me?

**Comment by thjaeckle** [comment]
Hi.

You are doing a lot of things already correctly.
One missing piece is to use the configured Javascript payload mapper in the "source" of your connection:
Look at the schema of connections here: https://www.eclipse.org/ditto/basic-connections.html#connection-model

The "sources" array contains a list of `Source` in which a `payloadMapping` array is defined.
This contains names of the payload mappers defined within your connection in `mappingDefinitions` (to enable reuse).
Your mapping definitions name is `javascript` (the UI uses that as default name).

So your source is missing:
```json
... 
  "payloadMapping": [ "javascript"] 
```

**Comment by thebist1234** [comment]
> Hi.
> 
> You are doing a lot of things already correctly. One missing piece is to use the configured Javascript payload mapper in the "source" of your connection: Look at the schema of connections here: https://www.eclipse.org/ditto/basic-connections.html#connection-model
> 
> The "sources" array contains a list of `Source` in which a `payloadMapping` array is defined. This contains names of the payload mappers defined within your connection in `mappingDefinitions` (to enable reuse). Your mapping definitions name is `javascript` (the UI uses that as default name).
> 
> So your source is missing:
> 
> ```json
> ... 
>   "payloadMapping": [ "javascript"] 
> ```

Thank you for you feedback. I changed it as you can see in[ this picture ](https://ibb.co/ZB3ZzRH) but I got the same error again.

**Comment by thjaeckle** [comment]
You added it to the `"replyTarget"` instead of the source.
So pull it up one json level.

**Comment by thebist1234** [comment]
> You added it to the `"replyTarget"` instead of the source. So pull it up one json level.

Yeh, It's done, what if I want to add "payloadMapping" while I'm creating the connection or modify it. can I do that without UI?

**Comment by thjaeckle** [comment]
> what if I want to add "payloadMapping" while I'm creating the connection or modify it. can I do that without UI? because when I want to create a new connection using API I need to add it too. thank you.

Yes, of course - the UI just helps on the formatting (e.g. replacing linebreaks with `\n` in the inlined javascript of the connection).

**Comment by thebist1234** [comment]
> 

thanks for your help.
