### ISSUE TITLE
Connect ditto with hono

### ISSUE THREAD

**Issue by pavithvishnu** [eclipse-ditto/ditto#1634]
I have deployed hono is AKS, and ditto is deployed as a docker container in vm. I need to create a connection between my hono and ditto.
Can anyone provide me the detailed steps which need to be followed?

**Comment by thjaeckle** [comment]
The Eclipse IoT Packages project provides a connection template showing a possible connection configuration to connect to Hono via Kafka:
https://github.com/eclipse/packages/blob/master/packages/cloud2edge/post-install/hono-kafka-connection.json

This should be a good starting point.
Apart from that there is plenty of documentation to explore.

**Comment by pavithvishnu** [comment]
hi @thjaeckle,
thanks for pointing me to the document, i have followed the document and deployed the c2e package on the AKS, and try out the examples mentioned in that, but i was unable to create a new connection between hono and ditto, i have try both amqp and kafka based connection setting, none of them works.
problem:
1) AMQP as mentioned in doc (dispatch-router container is not created i have follow the this link to install c2e  [https://www.eclipse.org/packages/prereqs/](url))
curl -i -X POST -u devops:${DITTO_DEVOPS_PWD} -H 'Content-Type: application/json' --data '{
  "targetActorSelection": "/system/sharding/connection",
  "headers": {
    "aggregate": false
  },
  "piggybackCommand": {
    "type": "connectivity.commands:createConnection",
    "connection": {
      "id": "hono-connection-for-'"${HONO_TENANT}"'",
      "connectionType": "amqp-10",
      "connectionStatus": "open",
      "uri": "amqp://consumer%40HONO:verysecret@'"${RELEASE}"'-dispatch-router-ext:15672",
      "failoverEnabled": true,
      "sources": [
        {
          "addresses": [
            "telemetry/'"${HONO_TENANT}"'",
            "event/'"${HONO_TENANT}"'"
          ],
          "authorizationContext": [
            "pre-authenticated:hono-connection"
          ],
          "enforcement": {
            "input": "{{ header:device_id }}",
            "filters": [
              "{{ entity:id }}"
            ]
          },
          "headerMapping": {
            "hono-device-id": "{{ header:device_id }}",
            "content-type": "{{ header:content-type }}"
          },
          "replyTarget": {
            "enabled": true,
            "address": "{{ header:reply-to }}",
            "headerMapping": {
              "to": "command/'"${HONO_TENANT}"'/{{ header:hono-device-id }}",
              "subject": "{{ header:subject | fn:default(topic:action-subject) | fn:default(topic:criterion) }}-response",
              "correlation-id": "{{ header:correlation-id }}",
              "content-type": "{{ header:content-type | fn:default('"'"'application/vnd.eclipse.ditto+json'"'"') }}"
            },
            "expectedResponseTypes": [
              "response",
              "error"
            ]
          },
          "acknowledgementRequests": {
            "includes": [],
            "filter": "fn:filter(header:qos,'"'"'ne'"'"','"'"'0'"'"')"
          }
        },
        {
          "addresses": [
            "command_response/'"${HONO_TENANT}"'/replies"
          ],
          "authorizationContext": [
            "pre-authenticated:hono-connection"
          ],
          "headerMapping": {
            "content-type": "{{ header:content-type }}",
            "correlation-id": "{{ header:correlation-id }}",
            "status": "{{ header:status }}"
          },
          "replyTarget": {
            "enabled": false,
            "expectedResponseTypes": [
              "response",
              "error"
            ]
          }
        }
      ],
      "targets": [
        {
          "address": "command/'"${HONO_TENANT}"'",
          "authorizationContext": [
            "pre-authenticated:hono-connection"
          ],
          "topics": [
            "_/_/things/live/commands",
            "_/_/things/live/messages"
          ],
          "headerMapping": {
            "to": "command/'"${HONO_TENANT}"'/{{ thing:id }}",
            "subject": "{{ header:subject | fn:default(topic:action-subject) }}",
            "content-type": "{{ header:content-type | fn:default('"'"'application/vnd.eclipse.ditto+json'"'"') }}",
            "correlation-id": "{{ header:correlation-id }}",
            "reply-to": "{{ fn:default('"'"'command_response/'"${HONO_TENANT}"'/replies'"'"') | fn:filter(header:response-required,'"'"'ne'"'"','"'"'false'"'"') }}"
          }
        },
        {
          "address": "command/'"${HONO_TENANT}"'",
          "authorizationContext": [
            "pre-authenticated:hono-connection"
          ],
          "topics": [
            "_/_/things/twin/events",
            "_/_/things/live/events"
          ],
          "headerMapping": {
            "to": "command/'"${HONO_TENANT}"'/{{ thing:id }}",
            "subject": "{{ header:subject | fn:default(topic:action-subject) }}",
            "content-type": "{{ header:content-type | fn:default('"'"'application/vnd.eclipse.ditto+json'"'"') }}",
            "correlation-id": "{{ header:correlation-id }}"
          }
        }
      ]
    }
  }
}' http://${DITTO_API_IP}:${DITTO_API_PORT_HTTP}/devops/piggyback/connectivity

2) Kafka based connection:
i have trying deploying the ditto as docker container, also as helm package, also with c2e package. in all the cases, whenever i try to create a kafka connection using connectivity api and piggyback command. connectivity containers starts to crashs in loop.  there is no recovery for it.

can you please help me out with it.?

**Comment by pavithvishnu** [comment]
There is an update, I have modified the yaml file. Now I have able to create a connection between hono and ditto using amqp. 
but if I send the data from the device to hono it is not reflecting in ditto.

**Comment by thjaeckle** [comment]
Please provide the logs of Ditto's `connectivity` container. This should give an insight in the potential configuration errors.
