### ISSUE TITLE
Geospatial Search support

### ISSUE THREAD

**Issue by rpahli** [eclipse-ditto/ditto#1636]
I know the there is no real semantic for the data stored in ditto. My question is, is it possible to seach for geo locations or for things within a range or is there a plan to support it?

**Comment by thjaeckle** [comment]
No, that is neither currently supported nor planned to support.

It could maybe be added to Ditto, using MongoDB's [Geospatial Queries](https://www.mongodb.com/docs/manual/geospatial-queries/) - but this needs concept and development of that feature.
