### ISSUE TITLE
Tracing misbehaviour when service under load

### ISSUE THREAD

**Issue by vvasilevbosch** [eclipse-ditto/ditto#1645]
Incomplete tracing is observed, while load testing the service with modify thing commands, via kafka connection. What can be seen on the trace, is that there are spans with invalid parent span IDs and also a lot of missing spans that should be there. I attach json export of two traces(complete and incomplete) as well as screenshot from jaeger ui.
![jaeger-invalid-parent-span-ids](https://github.com/eclipse-ditto/ditto/assets/112558685/5b247c75-efbc-4463-96c5-360e33d410c7)
[traces.zip](https://github.com/eclipse-ditto/ditto/files/11592669/traces.zip)

**Comment by vvasilevbosch** [comment]
@thjaeckle I have the following setup: 1_000_000 things, 8 connectivity,policies,things, 1 things-search and 1 gateway, 1 kafka connection with 8 clients, to which I send 5000 modifyThing messages per second. I will further check the Kamon configuration. Thanks!

**Comment by thjaeckle** [comment]
Ok, with this load I would expect that you would have to scale your Jaeger backend.
Every command will cause at least 5 spans of a trace, reported via at least 3 services in Ditto.

More realistic IMO would be to configure that only eg 1% of the requests are sampled..

**Comment by vvasilevbosch** [comment]
I tried increasing the buffer size of the tracing reporter, but it seems there is a bug in the Kamon library, I have raised an issue in their repo: https://github.com/kamon-io/Kamon/issues/1281

Closing this issue
