### ISSUE TITLE
ditto with raspberry grove-ctrl - webapp setup info needed

### ISSUE THREAD

**Issue by mdgramma** [eclipse-ditto/ditto#1646]
Dear Thomas,

We are trying to experiment by developing a simple performance-related digital twin for a biosensor using eclipse ditto and ditto-examples/grove-ctl. 

Therefore, we started by setting up a platform with a PC running Linux and connect this to a Raspberry equipped with grove light sensor (via GrovePi shield), following the steps in: https://github.com/eclipse-ditto/ditto-examples/tree/master/grove-ctrl

Everything goes well with adding the raspberry sensor "thing" to ditto on the PC.
Also, we can also perform PUT/GET (http) operations on the thing:
a) curl -u ditto:ditto -X PUT   -H 'Content-Type: application/json' -d '99'
'http://192.168.0.101:8080/api/2/things/org.eclipse.ditto.example:pi/features/IlluminanceSensor_0/properties/sensorValue'
to directly change property sensor values, and
b) curl -u ditto:ditto -X GET 'http://192.168.0.101:8080/api/2/things/org.eclipse.ditto.example:pi/features/IlluminanceSensor_0/properties/sensorValue' to view the new data.

However, we fail to connect from Raspberry to the thing via the websocket interface (by running: python 3 ditto_grove_demo.py, which uses ws/1 interface), with the following error recorded from ditto:
Error 403 -- ... the requester had insufficient permissions to modify it (WRITE is required)

Perhaps, we don't quite understand how to set up the WebUI connected to Ditto. Although, we compiled the webapp fine (using npm install, updating the http download sites),when we open webapp/index.html from ditto-master/deployment/docker directory, there are no updates at all (automatically or manually). 

Unfortunately, the instructions are missing in https://github.com/eclipse-ditto/ditto-examples/tree/master/grove-ctrl
This url states (few lines above the Section "Setting up the Raspberry Pi"): 
"After creating our Thing, we can commence by opening the WebUI for the first time. @Todo: Philipp" (maybe this refers to Philipp Michalski)

Can you please help? 

Thank you in advance.

Miltos

**Comment by mdgramma** [comment]
Dear Thomas,

Thank you for the quick response.

I understand the situtation

Since http interface works fine, we plan to develop over it and skip 
websockets for the time being.

Perhaps, once done, we can help update this part, which may be 
interesting for those working on edge computing or below.

By the way, do you think that ditto is able to operate in an industrial 
environment with lots of sensors?
Do you know of any study related to it?

We appreciate your help.

Best regards,

Miltos

**Comment by BobClaerhout** [comment]
We are indeed using it in an industrial context. However, we are not anywhere near reaching 5000 modifyThing msg/s at the moment. We are currently looking into how we can improve this but this doesn't have our primary focus since we are currently managing the operational required load. This is WIP and we need to improve over time.

**Comment by elewah** [comment]
@mdgramma 
in ditto_grove_demo.py at start_websocket() function
change the API version as the current version is 2. I able to connect 
`ws_address = "ws://" + DITTO_IP + ":" + DITTO_PORT + "/ws/2"`
another thing is to change the user and password to be ditto
I tried personally to add another user, as mentioned in the documentation that changed, but I couldn't
`# User and password needed for providing new sensor values.`
`THING_USER = "ditto" `
`THING_PASSWORD = "ditto"` 

Are you able to add the Raspberry user?
