### ISSUE TITLE
[Helm,Gateway] devopsPassword and statusPassword wrong values.yaml path

### ISSUE THREAD

**Issue by mladBlum** [eclipse-ditto/ditto#1670]
In templates/gateway-secret.yaml the devopsPassword and statusPassword are read from `.Values.gateway.devopsPassword` and `.Values.gateway.statusPassword`.

In the deployment/helm/ditto/values.yaml these two values are located at `gateway.config.devops.devopsPassword` and `gateway.config.devops.statusPassword`

As a result, the two passwords are always regenerated and the passed passwords are not used.

**Comment by thjaeckle** [comment]
Thanks for the hint, will fix in #1671
