### ISSUE TITLE
404 on UI js and css assets when launched with docker compose

### ISSUE THREAD

**Issue by samrose** [eclipse-ditto/ditto#1707]
Using the latest release of ditto

ui loads with these errors on Ubuntu 22.04.2 LTS in all browsers on the same machine (chrome, firefox, etc)

![image](https://github.com/eclipse-ditto/ditto/assets/115821/0231a538-cce6-4a73-8110-94cb00c21a4b)

**Comment by thjaeckle** [comment]
You probably need to build it - when running the `docker-compose.yml`, the UI is served from the local file path.

See here for the building instructions: https://github.com/eclipse-ditto/ditto/tree/master/ui#getting-started

**Comment by thjaeckle** [comment]
@thfries it would probably make more sense in using the latest Ui release in the Docker compose file.
Can you work without the UI being served from the local file system by default?

**Comment by thfries** [comment]
Yes, no problem at all. I'm using esbuild serve and not the local filesystem. I was thinking in a similar direction -> UI should be built by default and included.

**Comment by samrose** [comment]
I'd be interested in contributing toward this if that can work? Do we just need to run npm run build in the Dockerfile? esbuild or bun actually are better/faster alternatives any objection to those?

**Comment by samrose** [comment]
...I see now this project already uses esbuild

**Comment by thjaeckle** [comment]
@samrose we would just have to adjust the Docker compose file to use the Ditto UI Image from docker hub:
https://registry.hub.docker.com/r/eclipse/ditto-ui

Same to the other services.

**Comment by thfries** [comment]
Sounds good. Would you mind to provide a small PR for that?

**Comment by thjaeckle** [comment]
I already took the liberty of doing so .. #1711
