### ISSUE TITLE
Hono connection can't be created for Hono tenant with '.' in name

### ISSUE THREAD

**Issue by calohmn** [eclipse-ditto/ditto#1748]
When trying to create a Hono connection for a Hono tenant that contains a dot in the name (e.g. `org.eclipse.packages.c2e` as used in the IoT packages cloud2edge chart), there is an error.
```
PUT /api/2/connections/org.eclipse.packages.c2e
{"status":400,
"error":"connectivity:connection.id.invalid",
"message":"The Connection ID 'org.eclipse.packages.c2e' is not valid.",
"description":"It must be conform to the regular expression: <[a-zA-Z0-9-_:]{1,100}>."}
```

This limitation is currently not documented.

I wonder whether there could be an alternative way to pass on the Hono tenant ID  in the connection data.
The current way of using the connection ID also doesn't look very intuitive to me.
Wouldn't it be possible to use a connection configuration containing something like
```
"specificConfig": {
  "honoTenant": "org.eclipse.packages.c2e"
} 
```
here?

**Comment by thjaeckle** [comment]
Yes, the alternative way would work well 👍 
It could fall back to the connectionId, of this is not present - in a similar way the MQTT "clientId" is configured.

AFAIK you are the first user of this "hono" connection type, @calohmn - so thanks for being the early adopter ;)
