### ISSUE TITLE
Correct handling of special MQTT headers in MQTT 5

### ISSUE THREAD

**Issue by dimabarbul** [eclipse-ditto/ditto#1758]
MQTT 5 has some special headers: mqtt.topic, mqtt.qos, mqtt.retain.

1. When I send message and set, for example, mqtt.retain header (using headerMapping or payload mapper), it will be applied (i.e., the message will be retained) **and added to MQTT user properties**. These special headers should not be added to user properties.
2. When I receive message using MQTT 5, the headers are set accordingly to message features, for example, mqtt.topic will contain topic name that the message was received on. But if the message has user property mqtt.topic, it will override special meaning of the header and contain whatever user property contains. User properties which named exactly as special MQTT headers should be ignored.

**Comment by dimabarbul** [comment]
I believe, the same should apply to correlation-id, content-type and reply-to headers.

**Comment by dimabarbul** [comment]
I've found [comment](https://github.com/eclipse-ditto/ditto/blob/b80497dfc6cc87839d19143f0b9ddc995edfea4f/connectivity/service/src/main/java/org/eclipse/ditto/connectivity/service/messaging/mqtt/hivemq/publishing/ExternalMessageToMqttPublishTransformer.java#L50) about known MQTT headers in outgoing message stating that they weren't removed because it would break functionality for users who already depend on it.
@thjaeckle, should feature toggle be introduced, e.g., ditto.connectivity.feature.mqtt-known-headers-in-user-properties-enabled?

**Comment by thjaeckle** [comment]
> @thjaeckle, should feature toggle be introduced, e.g., ditto.connectivity.feature.mqtt-known-headers-in-user-properties-enabled?

Oh, yes .. indeed - I vaguely remember discussing that some time ago.
Controlling it with a feature toggle would make sense, yes.

We have already some feature toggles defined here - so I would prefer to add the feature toggle in the same way.
https://github.com/eclipse-ditto/ditto/blob/2c94cc284c8d7250af9596e4d4a4c51748799dd7/internal/utils/config/src/main/resources/ditto-devops.conf#L10-L23

Here is how feature toggles are evaluated currently:
https://github.com/eclipse-ditto/ditto/blob/master/base/model/src/main/java/org/eclipse/ditto/base/model/signals/FeatureToggle.java

**Comment by thjaeckle** [comment]
@dimabarbul would you like to provide this for Ditto 3.4.0 (which we want to release in the next 1-2 weeks)?

**Comment by dimabarbul** [comment]
Yes, I would love to.
