### ISSUE TITLE
Issue in Jenkins_multibranch_pipeline.

### ISSUE THREAD

**Issue by Korakbhakta02** [eclipse-ditto/ditto#1795]
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16:22 min (Wall Clock)
[INFO] Finished at: 2023-11-06T06:06:36Z
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "ditto" could not be activated because it does not exist.
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:3.1.1:deploy (default-deploy) on project ditto: Failed to deploy artifacts: Could not transfer artifact org.eclipse.ditto:ditto:pom:0-main-20231106.055013-1 from/to repo.eclipse.org (https://repo.eclipse.org/content/repositories/ditto-snapshots/): authentication failed for https://repo.eclipse.org/content/repositories/ditto-snapshots/org/eclipse/ditto/ditto/0-main-SNAPSHOT/ditto-0-main-20231106.055013-1.pom, status: 401 Unauthorized -> [Help 1]

This issue is being faced when I am trying to build the pipeline. It is during the "build" stage:

 stage('Build') {
            agent {
                docker {
                    args "--privileged -u root"
                    image "maven:3.8.4-openjdk-17"
                    reuseNode true
                }
            }
            steps {
                configFileProvider([configFile(fileId: 'mvn-bdc-settings', variable: 'MVN_SETTINGS')]){
                    sh "mvn -s $MVN_SETTINGS  clean deploy javadoc:jar source:jar " +
                               "-T1C --batch-mode --errors " +
                               "-Pditto " +
                               "-Drevision=${theVersion} " +
                               "${params.EXTRA_MAVEN_ARGS ?: ''}"
               } 
            }
            post {
                always {
                    junit allowEmptyResults: true, testResults: "**/test-reports/*.xml,**/**/target/surefire-reports/*.xml,**/**/**/target/surefire-reports/*.xml,**/**/**/target/failsafe-reports/*.xml,**/**/target/failsafe-reports/*.xml"
                }
            }
        }

**Comment by thjaeckle** [comment]
Hi @Korakbhakta02
This pipeline is not intended for building Ditto, but for building feature branches.

In order to build Ditto, please refer to the [README.md](https://github.com/eclipse-ditto/ditto/blob/master/README.md). Section "Development Guide".

**Comment by Korakbhakta02** [comment]
Does the feature branches means things,thing search,etc? And also when I build the jenkins_multibranch_pipeline script, it gives authentication error for repo.eclipse.org?what are the credentials to be set in the config file for the authentication?

**Comment by thjaeckle** [comment]
As I said:
> This pipeline is not intended for building Ditto, but for building feature branches.

Please don't use this `jenkins_multibranch_pipeline` file as Jenkins pipeline. It is for (Bosch) internal use only.
No, feature branches do not mean things,thing search, etc.

As I said:
> In order to build Ditto, please refer to the [README.md](https://github.com/eclipse-ditto/ditto/blob/master/README.md). Section "Development Guide".
