### ISSUE TITLE
Multiple sort options in combinations with cursor fails. Invalid handling of comma.

### ISSUE THREAD

**Issue by alstanchev** [eclipse-ditto/ditto#1797]
A search query that uses nore than one sort property is not handled properly **_sort(-attributes/type,+features/some),size(200),cursor(...)_**.

In the case where there is no cursor there is no error. But in case a cursor is included the problem manifests.

In [ThingSearchRoute](https://github.com/eclipse-ditto/ditto/blob/d008959c019a966af0c1b152c12f953002669c58/gateway/service/src/main/java/org/eclipse/ditto/gateway/service/endpoints/routes/thingsearch/ThingSearchRoute.java#L122C59-L122C59) in the [calculateOptions](https://github.com/eclipse-ditto/ditto/blob/d008959c019a966af0c1b152c12f953002669c58/gateway/service/src/main/java/org/eclipse/ditto/gateway/service/endpoints/routes/thingsearch/ThingSearchRoute.java#L203) method options are parsed by comma which leads to incorectly dividing the **sort** part and leading to 
`{
    "status": 400,
    "error": "thing-search:search.option.invalid",
    "message": "Invalid input '+', expected Sort, Limit, Cursor or Size (line 1, column 35):\nsort(-/attributes/type,+/thingId),+thingId),size(2),cursor(....)\n,
    "description": "At least one provided option is invalid."
}`

**Comment by thjaeckle** [comment]
@alstanchev do you expect to provide a fix soon? #1798 is really a blocker for us, so I would want to quickly build a 3.4.1 bugfix release.

**Comment by alstanchev** [comment]
Yes, it is ready. Just want to wait for the system tests to be sure. Will push it tomorrow.
