### ISSUE TITLE
Docker container log file fills up disk

### ISSUE THREAD

**Issue by marioverhaeg** [eclipse-ditto/ditto#1803]
Hi,
I'm running Ditto based on the docker compose script. After a while my disk is running out of disk space. This seems to be related to the size of the log file. This is growing without limits in all containers.

-rw-r----- 1 root root 11750122173 Nov 11 07:28 0d86f44b961c545a6b4eb00e1ef627dfecc5d33af025748b5e33a3f6abdb6c87-json.log
drwx------ 2 root root        4096 Oct 27 10:09 checkpoints
-rw------- 1 root root        7319 Nov 11 07:28 config.v2.json
-rw-r--r-- 1 root root        1552 Nov 11 07:28 hostconfig.json
-rw-r--r-- 1 root root          13 Oct 27 10:09 hostname
-rw-r--r-- 1 root root         174 Oct 27 10:09 hosts
drwx--x--- 3 root root        4096 Oct 27 10:09 mounts
-rw-r--r-- 1 root root          38 Oct 27 10:09 resolv.conf
-rw-r--r-- 1 root root          71 Oct 27 10:09 resolv.conf.hash

In this container it has grown over 11GB.

Docker compose has ways to limit log file consumption. Would it be possible to embed this?
https://stackoverflow.com/questions/31829587/docker-container-logs-taking-all-my-disk-space

Mario

**Comment by thjaeckle** [comment]
Hi.
If course, if this helps you, a Pull Request is welcome.
I do not really expect docker compose to be used for productive scenarios, but we will accept contributions improving on that.

**Comment by marioverhaeg** [comment]
Hi Thomas,
That will be my first PR ever, but I'll take your suggestion as a small challenge :-) . I'll do some testing first and will come back to this.

**Comment by marioverhaeg** [comment]
Hi Thomas,
I followed the contribution guide and created PR: #1831 . Please let me know if this is the right way to contribute. Thanks!

**Comment by thjaeckle** [comment]
Closed via #1831
