### ISSUE TITLE
Enhancement Proposal: Addressing Operations Tab UI Issue with Logger Creation and Level Buttons

### ISSUE THREAD

**Issue by aitiqad** [eclipse-ditto/ditto#1809]
There is an issue with the Operations tab UI. I am uncertain whether you have intentionally retained this feature. In the text field for adding a new logger, I suggest disabling the level buttons. I observed that, even when the text box is empty, it is possible to send a PUT request using the buttons, thereby creating an empty logger with associated levels.

**Comment by thjaeckle** [comment]
That seems not to be wanted, indeed.

**Comment by thjaeckle** [comment]
@aitiqad why did you close the issue? 
I agree that this can be improved by not allowing to click the "level" buttons when no text is in the box yet.

**Comment by aitiqad** [comment]
I thought, since you have taken this issue into account, I would go ahead and close it.

**Comment by sejal-bansal** [comment]
@aitiqad @thjaeckle I would like to work on this issue. Could you please assign it to me?

**Comment by thfries** [comment]
Hello @sejal-bansal,
sorry I was not aware that this issue is assigned. It was not my intention to surge ahead. Apologize.
@thjaeckle, I'd better in future ask for assignment before working on tickets.

once again, sorry

**Comment by thjaeckle** [comment]
@aitiqad the UI is a "helper" to send [DevOps commands](https://eclipse.dev/ditto/installation-operating.html#devops-commands), also sometimes referred to as [piggyback commands](https://eclipse.dev/ditto/installation-operating.html#piggyback-commands).

The Operations tab also allows easily adjusting the [log levels dynamically](https://eclipse.dev/ditto/installation-operating.html#dynamically-adjust-log-levels).

I am afraid there is no documentation on the UI itself.

**Comment by aitiqad** [comment]
> @aitiqad the UI is a "helper" to send [DevOps commands](https://eclipse.dev/ditto/installation-operating.html#devops-commands), also sometimes referred to as [piggyback commands](https://eclipse.dev/ditto/installation-operating.html#piggyback-commands).
> 
> The Operations tab also allows easily adjusting the [log levels dynamically](https://eclipse.dev/ditto/installation-operating.html#dynamically-adjust-log-levels).
> 
> I am afraid there is no documentation on the UI itself.

Thank you for the Info @thjaeckle
