### ISSUE TITLE
 Issue with k6 Test Execution and Missing k6-test-secret

### ISSUE THREAD

**Issue by itsUtkarsh2306** [eclipse-ditto/ditto#1838]
Hello,

I'm currently setting up a benchmarking environment for Ditto with the following components:

1. Ditto running on Kubernetes.
2. Kafka, mmock, and k6-operator also running on Kubernetes.
3. All the tests have been uploaded as per the documentation.
During the execution of the tests using the command k create -f k6-ditto-benchmark-test.yaml, I encountered an error indicating that the k6-test-secret was not found. This secret is not present in the directory, nor is it mentioned in any of the provided YAML files.

Could you please provide guidance on what should be included in the k6-test-secret and how we can configure it correctly?

**Comment by thjaeckle** [comment]
@vvasilevbosch could you please have a look?

**Comment by vvasilevbosch** [comment]
I will check this

**Comment by vvasilevbosch** [comment]
The benchmark test does not use any secrets. I ran ran the benchmark locally and noticed I have left a env var that is unused, and perhaps causing the issue - 'AUTHORIZATION_HEADER_VALUE'. I will open a PR soon, but I hit some other issues with xk6-kafka as well, they seem to have changed the type of a property, that is used and the benchmark is not working with xk6-kafka >= 20.0.0.

**Comment by vvasilevbosch** [comment]
Follow this PR, after it's merged, it should all be working #1849

**Comment by itsUtkarsh2306** [comment]
I tried running the latest benchmark.I followed every steps and I was able to see the kafka connection made and the connetion status is Open and succeeded, But then I am getting a error which says in the logs of k6-ditto-benchmark-test-1
time="2024-01-02T10:45:59Z" level=error msg="ReferenceError: connectionStatusError is not defined\n\tat setup (file:///test/k6-test.js:143:60(114))\n" hint="script exception"

**Comment by vvasilevbosch** [comment]
I clearly missed declaring this variable and didn't test out the creation of things after my refactor. I opened PR #1855

**Comment by vvasilevbosch** [comment]
#1855  is closed now, it should be all fine
