### ISSUE TITLE
Facing issue with probe while installing ditto through kubernetes

### ISSUE THREAD

**Issue by Korakbhakta02** [eclipse-ditto/ditto#1840]
While running ditto through kubernetes , the gateway pod is not getting ready as it is giving readiness and liveness probe error:
**Readiness probe failed: Get "http://{clusterIP}/ready": dial tcp clusterIP:8558: connect: connection refused**
**Liveness probe failed: Get "http://{clusterIP}/alive": dial tcp clusterIP:8558: connect: connection refused**
It will be helpful if any solution can be given to this.

**Comment by thjaeckle** [comment]
Please provide logs of the affected services.
