### ISSUE TITLE
Facing Authorization issue to up the Eclipse Ditto using Helm

### ISSUE THREAD

**Issue by kalyanibharadwaj** [eclipse-ditto/ditto#1841]
I'm encountering an authorization issue after deploying Eclipse Ditto using the Helm Chart with default values with docker desktop. The deployment process completed without any errors, and I followed the instructions to port forward and obtained the passwords for the "devops" and "status" accounts. 
However, upon attempting to access "http://devops:${DEVOPS_PWD}@localhost:8080/devops," I receive the message, **"The requested resource could not be found."** 

Additionally, I am unable to log in at "localhost:8080/ui" using the "devops" or "status" passwords.

 I would greatly appreciate any assistance in resolving this issue and would welcome any insights on where the problem may lie.

**Comment by kalyanibharadwaj** [comment]
adding additional information:
Helm Chart Version: 3.4.2

curl -i -X GET "http://devops:<devopspassword>@localhost:8080/devops
HTTP/1.1 404 Not Found
Server: nginx/1.25.3
Date: Thu, 14 Dec 2023 02:23:21 GMT
Content-Type: text/plain; charset=UTF-8
Content-Length: 42
Connection: keep-alive
Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE, OPTIONS
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: *

**Comment by thjaeckle** [comment]
3.4.2 had an issue with authentication, see https://github.com/eclipse-ditto/ditto/issues/1833

Did you try 3.4.3?

**Comment by kalyanibharadwaj** [comment]
observed same issue even with 3.4.3, i spend some time to debug and understand.
once i added the user under hashedBasicAuthUsers: its started working ...
