### ISSUE TITLE
sending ditto alerts and events through websocket to react client.

### ISSUE THREAD

**Issue by Nitishkrpatel** [eclipse-ditto/ditto#1850]
As per ditto documentation, WebSocket endpoint is given as  ws://dittoip:8080/ws/2. 
the alerts sent to this websocket endpoint should be accessable at react client. BUt failed to connect to ditto websocket from react client. 

here is my react code 

import React, { useEffect } from "react";

const WebSocketComponent = () => {
  useEffect(() => {
    // Replace "ws://localhost:8080/ws/2" with your actual WebSocket URL
    const websocketUrl = "ws://192.168.31.62:8080/ws/2";

    // Replace "ditto" and "ditto" with your actual credentials
    const username = "ditto";
    const password = "ditto";

    // Construct the Authorization header with HTTP Basic Authentication
    const credentials = `${username}:${password}`;
    const authHeader = `Basic ${btoa(credentials)}`;

    // Set up the WebSocket connection with the Authorization header
    const websocket = new WebSocket(websocketUrl, ["soap", "xmpp"], {
      headers: {
        Authorization: authHeader,
      },
    });

    // Event handler when the connection is opened
    websocket.onopen = () => {
      console.log("WebSocket connection opened");
    };

    // Event handler for incoming messages
    websocket.onmessage = (event) => {
      const message = JSON.parse(event.data);
      console.log("Received message:", message);
    };

    // Event handler when the connection is closed
    websocket.onclose = () => {
      console.log("WebSocket connection closed");
    };

    // Clean up the WebSocket connection on component unmount
    return () => {
      websocket.close();
    };
  }, []);

  return (
    <div>
      <p>WebSocket Example</p>
    </div>
  );
};

export default WebSocketComponent;

**Comment by thfries** [comment]
Can you pls try to add some commands like
```
ws.send('START-SEND-EVENTS');
ws.send('START-SEND-MESSAGES');
ws.send('START-SEND-LIVE-EVENTS');
ws.send('START-SEND-LIVE-COMMANDS');
```
in your `onopen` function of the web socket?

**Comment by Nitishkrpatel** [comment]
here is my code 

import React, { useEffect } from "react";

import { w3cwebsocket as W3CWebSocket } from "websocket";

const WebSocketComponent = () => {
  useEffect(() => {
    // Replace with your actual WebSocket URL
    const websocketUrl = "ws://192.168.31.62:8080/ws/2";

    // Create a new WebSocket instance using the w3cwebsocket from the websocket library
    const username = "ditto";
    const password = "ditto";

    // Corrected the syntax for credentials and authHeader
    const credentials = `${username}:${password}`;
    const authHeader = `Basic ${btoa(credentials)}`;

    const websocket = new W3CWebSocket(websocketUrl, ["soap", "xmpp"], {
      headers: {
        Authorization: authHeader,
      },
    });
    // Event handler for WebSocket errors
    websocket.onerror = (event) => {
      console.error("WebSocket Error:", event);

      // Additional details from the Event object
      console.error("Error Message:", event.message);
      console.error("Error Code:", event.code);
      console.error("Error Reason:", event.reason);
    };

    // Event handler when the connection is opened
    websocket.onopen = () => {
      console.log("WebSocket connection opened");
      websocket.send("START-SEND-EVENTS");
      websocket.send("START-SEND-MESSAGES");
      websocket.send("START-SEND-LIVE-EVENTS");
      websocket.send("START-SEND-LIVE-COMMANDS");

      // Example: Sending a message after connection
      websocket.send("Hello, WebSocket Server!");
    };

    // Event handler for incoming messages
    websocket.onmessage = (message) => {
      const parsedMessage = JSON.parse(message.data);
      console.log("Received message:", parsedMessage);
    };

    // Event handler when the connection is closed
    websocket.onclose = () => {
      console.log("WebSocket connection closed");
    };

    // Clean up the WebSocket connection on component unmount
    return () => {
      websocket.close();
    };
  }, []); // Empty dependency array ensures the effect runs once on mount

  return (
    <div>
      <p>WebSocket Example</p>
    </div>
  );
};

export default WebSocketComponent;



still facing connection error, find the screenshot of the browser console FYR.
![Screenshot from 2023-12-27 10-31-23](https://github.com/eclipse-ditto/ditto/assets/100232787/a2b34c38-a2c1-4847-b581-b3309844711d)

**Comment by thfries** [comment]
Sorry, I can not run your code. I just tried it out with local docker running ditto 3.4.0:
```
  let ws;
  try {
    ws = new WebSocket('ws://ditto:ditto@localhost:8080/ws/2');
    ws.onopen = () => {
      ws.onmessage = (message) => console.log(message);
      ws.onerror = (error) => console.log(error);
      ws.onclose = () => console.log('WebSocket closed');
      ws.send('START-SEND-EVENTS');
      ws.send('START-SEND-MESSAGES');
      ws.send('START-SEND-LIVE-EVENTS');
      ws.send('START-SEND-LIVE-COMMANDS');
    };
  } catch (error) {
    console.log(error);
  } 
```
It may be:
- providing username and password in the URL instead of the header
- not using W3CWebSocket

I hope this helps anyway.

**Comment by Nitishkrpatel** [comment]
it worked !  appreciate it, thanks a ton.
