### ISSUE TITLE
Sending TDengine kafka topic message to ditto.

### ISSUE THREAD

**Issue by sushmasub10** [eclipse-ditto/ditto#1857]
hello,
Using TDengine source connect im able to send data to kafka topic , how do i read message from this kafka topic on ditto.
i have done configuration like this : 

curl -i -X POST -u devops:foobar -H "Content-Type: application/json"  -d '{
  "connection": {
    "id": "kafka-example-connection-123",
    "connectionType": "kafka",
    "connectionType": "kafka",
    "connectionStatus": "open",
    "failoverEnabled": true,
    "uri": "tcp://localhost:9092",
    "specificConfig": {
      "bootstrapServers": "localhost:9092",
      "saslMechanism": "plain"
    },
    "sources": [
      {
        "addresses": ["tdengine-test-meters"],
        "consumerCount": 1,
        "qos": 1,
        "authorizationContext": ["ditto:inbound-auth-subject"],
        "enforcement": {
          "input": "{{ header:device_id }}",
          "filters": ["{{ entity:id }}"]
        },
        "headerMapping": {},
        "payloadMapping": ["json"],
        "replyTarget": {
          "enabled": true,
          "address": "theReplyTopic",
          "headerMapping": {},
          "expectedResponseTypes": ["response", "error", "nack"]
        },
        "acknowledgementRequests": {
          "includes": []
        },
        "declaredAcks": []
      }
    ],
    "targets": [
      {
        "address": "topic/key",
        "topics": [
          "_/_/things/twin/events",
          "_/_/things/live/messages"
        ],
        "authorizationContext": ["ditto:outbound-auth-subject"]
      }
    ]
  }
}' http://localhost:8080/api/2/connections
HTTP/1.1 400 Bad Request
Server: nginx/1.21.6
Date: Fri, 05 Jan 2024 10:03:12 GMT
Content-Type: application/json
Content-Length: 170
Connection: keep-alive

{"status":400,"error":"json.field.missing","message":"JSON did not include required </connectionType> field!","description":"Check if all required JSON fields were set."}

**Comment by thjaeckle** [comment]
This is not valid JSON:
```json
{
  "connectionType": "kafka",
  "connectionType": "kafka"
}
```

That could be the issue.

**Comment by sushmasub10** [comment]
Hello thanks for the response, 
i tried to fix it with singe,
 {"connectionType":"kafka"}
it still doesn't work.

**Comment by thjaeckle** [comment]
Then you send something else not conforming to what is expected.
You should check your payload.
