### ISSUE TITLE
Steps for increasing the maximum size for paging

### ISSUE THREAD

**Issue by Korakbhakta02** [eclipse-ditto/ditto#1873]
Present maximum size for paging is 200 for things. But the items created are more than 200 and in future, more things will be created. All these things are to be presented. so, what are the steps to remove the maximum limit?

**Comment by thjaeckle** [comment]
That's what you would use [pagination](https://dev.to/pragativerma18/unlocking-the-power-of-api-pagination-best-practices-and-strategies-4b49) for.
Ditto documentation see: https://eclipse.dev/ditto/basic-search.html#sorting-and-paging-options
HTTP API docs see: https://eclipse.dev/ditto/http-api-doc.html#/Things-Search/get_api_2_search_things

**Comment by Korakbhakta02** [comment]
But that pagination limit is also 200. If I want to get the list of items which is more than 200, how to get?

**Comment by alstanchev** [comment]
As pointed in the documentation provided by @thjaeckle you would receive a cursor in the response if the result is more than the page size. You would include it in the second request so that you would receive the second page and so on.
