### ISSUE TITLE
commands to device

### ISSUE THREAD

**Issue by sushmasub10** [eclipse-ditto/ditto#1885]
can you please provide an example of how to send command to device from eclipse ditto ? And what is the difference between sending message as TURNOFF and command as TURNOFF ?

**Comment by thfries** [comment]
Hello @sushmasub10,

See also [here](https://eclipse.dev/ditto/protocol-twinlive.html)

**Option 1: Use live channel: Send a message to the device (bypassing the twin) - device receives the message**

Example via HTTP API:
```
POST http://localhost:8080/api/2/things/org.eclipse.ditto:4711/features/fan/inbox/messages/TURNOFF?timeout=0
```
This will generate the following ditto message:
```
{
  "topic": "org.eclipse.ditto/4711/things/live/messages/TURNOFF",
  "headers": {...},
  "path": "/features/fan/inbox/messages/TURNOFF"
}
```

**Option 2: Use twin channel: Send a command to modify the twin - device receives a "modified" event**

Example via HTTP API:
```
PUT http://localhost:8080/api/2/things/org.eclipse.ditto:4711/features/fan
```
with payload
```
{
  "desiredProperties": {
    "state": "OFF"
  }
}
```
This will generate the following ditto message:
```
{
  "topic": "org.eclipse.ditto/4711/things/twin/events/modified",
  "headers": {...},
  "path": "/features/fan",
  "value": {
    "desiredProperties": {
      "state": "OFF"
    }
  }
}
```

**Precondition**
Both options requires the device to subscribe to receive these messages. E.g. the device is connected to a MQTT broker and you have a ditto connection to this broker with a **target** like this:
```
{
      "address": "eclipse-ditto-sandbox/c/{{ thing:id }}",
      "topics": [
        "_/_/things/twin/events",
        "_/_/things/live/messages"
      ],
      "qos": 0,
      "authorizationContext": [
        "nginx:ditto"
      ],
      "headerMapping": {}
    }
```
And your device is subscribing like this:
```
mosquitto_sub -h test.mosquitto.org -p 1883 -t eclipse-ditto-sandbox/c/org.eclipse.ditto:4711
```

**Comment by sushmasub10** [comment]
Thank you so much.

**Comment by Lcq2002** [comment]
Why is it that I can see subscribed messages on mqttx using the twin channel, but not using the live channel?
