### ISSUE TITLE
Helm chart: Update MongoDB chart dependency to 13.x (MongoDB 6)

### ISSUE THREAD

**Issue by calohmn** [eclipse-ditto/ditto#1892]
In the ditto Helm chart, the mongoDB chart dependency is set to version `^12.x`, the latest version to match that being `12.1.31`.
That version uses the bitnami `common` chart version `1.16.1`.

With bitnami `common` chart version `2.9.0`, there has been an incompatible change in the `common.labels.standard` named template.
This means, that when using the ditto chart together with another bitnami chart that uses the `common` chart >= 2.9 (e.g. the newest Kafka chart), there may be an error like
```
template: cloud2edge/charts/hono/charts/kafka/templates/rbac/serviceaccount.yaml:12:14: 
executing "cloud2edge/charts/hono/charts/kafka/templates/rbac/serviceaccount.yaml" at <include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $)>: 
error calling include: template: cloud2edge/charts/ditto/charts/mongodb/charts/common/templates/_labels.tpl:6:27: 
executing "common.labels.standard" at <include "common.names.name" .>: 
error calling include: template: cloud2edge/charts/ditto/charts/mongodb/charts/common/templates/_names.tpl:6:18: 
executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name
```
(see also https://github.com/bitnami/charts/issues/19417).

The above error is from testing the Eclipse IoT Packages cloud2edge chart with the upcoming Hono Helm chart version which references Kafka chart version 26.8.4 (see https://github.com/eclipse/packages/pull/523).

The solution here would be to update the mongoDB chart dependency in the ditto chart to at least `13.17.0` (or more generally `^13.x`, meaning `13.18.5`).

This would mean using a MongoDB 6 image though, the question there being whether ditto supports that version (https://eclipse.dev/ditto/installation-running.html#start-ditto only lists 5.0 as latest supported version).

**Comment by thjaeckle** [comment]
@kalinkostashki @alstanchev could you run the Ditto System-Tests against MongoDB 6.0 so that we can verify if this completely works?
I would assume so, but only update the dependency in the chart if we can verify that :)

**Comment by alstanchev** [comment]
@thjaeckle Tests look good running with mongo 6.0

**Comment by thjaeckle** [comment]
@alstanchev cool - could we then bump the mongo version used in ditto-tests permantently to MongoDB 6.0?
And we can also bump the bitnami mongoDB dependency to `^13.x`

I can provide that once I come to it ..

**Comment by alstanchev** [comment]
I don't see any reason not to.
