### ISSUE TITLE
Question regarding scalability in Ditto

### ISSUE THREAD

**Issue by aitiqad** [eclipse-ditto/ditto#1895]
Ditto API endpoints are taking longer time than usual (max time it took was 2.53secs on POSTMAN). What I found is that when the count of things exceeds 200~300 this issue occurs, hence I think there might be a scalability issue.
Question is can we make it more scalable? If so, how?

**Comment by thjaeckle** [comment]
How do you operate Ditto?
In a kubernetes cluster? Scaled to how many replicas? How many CPU requests and memory is configured?

I know of several installations of Ditto handling > 1 million things, if scaled properly.

**Comment by Korakbhakta02** [comment]
> How do you operate Ditto? In a kubernetes cluster? Scaled to how many replicas? How many CPU requests and memory is configured?
> 
> I know of several installations of Ditto handling > 1 million things, if scaled properly.

It is installed as a single instance in a kubernetes cluster and scaled to 1 replica only for now. Can you please provide the procedures for making it scalable enough to handle 1million things?

**Comment by thjaeckle** [comment]
This [blogpost](https://eclipse.dev/ditto/2023-10-09-ditto-benchmark.html) should give you enough information to get started.
