### ISSUE TITLE
mutiple ditto instance

### ISSUE THREAD

**Issue by sushmasub10** [eclipse-ditto/ditto#1896]
when i install eclipse ditto, it comes with default login with username and password (ditto:ditto) devops credentials(foobar for ngnix). 
How do i create multiple ditto instace for different user password and ngnix password ? kindly need your help.

**Comment by thjaeckle** [comment]
I am afraid I don't understand your question.
What are you trying to achieve and what problem do you have?

**Comment by sushmasub10** [comment]
Thanks for responding.
I need to create different eclipse ditto login accounts other than the default one which comes with ditto, ditto as username and password respectively. For different set of things i want to have different ditto accounts.

**Comment by thjaeckle** [comment]
You can use 2 options to authenticate users:
* ["pre-authentication"](https://eclipse.dev/ditto/installation-operating.html#pre-authentication)
   * e.g. using nginx for authentication
   * Ditto's Helm chart already provides an option to specify usernames and password via Helm config: https://github.com/eclipse-ditto/ditto/blob/4a6011be89556ab1bae69ada72a4e86f3e198f5f/deployment/helm/ditto/values.yaml#L71-L76
* [OpenID connect](https://eclipse.dev/ditto/installation-operating.html#openid-connect)

For a productive setup, I would always recommend using an OpenID connect provider, like for example Keycloak or a SaaS service like auth0.
