### ISSUE TITLE
EndPoint

### ISSUE THREAD

**Issue by JoyAlana** [eclipse-ditto/ditto#1909]
where to find endpoint class for renaming the endpoint?

**Comment by thjaeckle** [comment]
@JoyAlana could you please be more precise what your problem is or what you want to achieve?

**Comment by JoyAlana** [comment]
For example, I want to change the name of "thingId" to something else and also same in the endpoints ,like, instead of /things/thingId , it will be  /new-name/new-id-name.

So, can you help me with which folders shall I look into so that I can change the names and endpoints of ditto?

**Comment by thjaeckle** [comment]
The `ThingsRoute` contains all of the `/things` endpoints:
https://github.com/eclipse-ditto/ditto/blob/41d088a8f0bd027d6b7aaf2284208c18541598c9/gateway/service/src/main/java/org/eclipse/ditto/gateway/service/endpoints/routes/things/ThingsRoute.java#L135

**Comment by JoyAlana** [comment]
here if i changed the thingId into needed name will it works?

**Comment by thjaeckle** [comment]
You'll have to find out.

**Comment by JoyAlana** [comment]
where can i find the main class folder of all apis?

**Comment by thjaeckle** [comment]
1 folder up from the link I already provided to you before, did you read that message?
https://github.com/eclipse-ditto/ditto/tree/41d088a8f0bd027d6b7aaf2284208c18541598c9/gateway/service/src/main/java/org/eclipse/ditto/gateway/service/endpoints/routes
