### ISSUE TITLE
Things UI in ditto

### ISSUE THREAD

**Issue by VETRIVEL001** [eclipse-ditto/ditto#1918]
In Ditto UI, only showing limited number of things and also when I tried to hit [GET /api/2/things] its only returning things around 25.
I want to see all things which I stored. can anyone tell me where to extend this limit?

**Comment by thjaeckle** [comment]
See [documentation about pagination](https://eclipse.dev/ditto/basic-search.html#sorting-and-paging-options), supported on the `/api/2/search/things` API.
You can get up to `200` things per page, after that use the returned `cursor` to get the next page.

**Comment by VETRIVEL001** [comment]
By any chance, can i get more than 200 things?

**Comment by thfries** [comment]
In the UI, you can click `load more...` on the bottom of the list.
`25` per page is hard coded in the UI and not configurable. It can just be changed in the code (uncomment and replace `3` by `200`): https://github.com/eclipse-ditto/ditto/blob/f7b4b22c61f7f72b4d9cc7604ad85c923f2ee835/ui/modules/things/thingsSearch.ts#L181
As said by @thjaeckle, more than 200 require to use a `cursor`(this happens, when you use `load more...` in the UI).
