### ISSUE TITLE
Policy anounsments not working when connection is using namespace filtering

### ISSUE THREAD

**Issue by alstanchev** [eclipse-ditto/ditto#1920]
When a connection is subscribed to _/_/policies/announcements?namespaces=<some-namespace> the connection does not receive events with latest ditto version. If the namespace filter is removed events are received by the connection.
Strangely if the connection has two targets configured one with ns filtering and one without both publish the anouncement.
@thjaeckle i belive this is related to the latest pub-sub optimisations

**Comment by thjaeckle** [comment]
That could be, yes .. 
But don't we have system-tests for policy announcements? Maybe not with namespaces filter?

**Comment by alstanchev** [comment]
HI, @thjaeckle i'd apreciate a review. The change is very small.
