### ISSUE TITLE
how to use ditto-client send message to RabbitMQ (java)

### ISSUE THREAD

**Issue by peng9fei** [eclipse-ditto/ditto#1949]
I want to create a java project,send the collected data through eclipse ditto to RabbitMQ.
I should create a connection:
```json
{
  "connection": {
    "id": "rabbit-example-connection-123",
    "connectionType": "amqp-091",
    "connectionStatus": "open",
    "failoverEnabled": true,
    "uri": "amqp://guest:guest@localhost:5672",
    "sources": [
      {
        "addresses": [
          "queueName"
        ],
        "authorizationContext": ["ditto:inbound-auth-subject", "..."]
      }
    ],
    "targets": [
      {
        "address": "exchangeName/routingKey",
        "topics": [
          "_/_/things/twin/events",
          "_/_/things/live/messages"
        ],
        "authorizationContext": ["ditto:outbound-auth-subject", "..."]
      }
    ]
  }
}
```

but i don't know how to use the connection to send message。
could give me a java example?

**Comment by thjaeckle** [comment]
[Sending messages](https://eclipse.dev/ditto/basic-messages.html#apis) can e.g. be done via the HTTP API:
https://eclipse.dev/ditto/http-api-doc.html#/Messages/post_api_2_things__thingId__inbox_messages__messageSubject_

If you configured your connection for "target" "topic" `"_/_/things/live/messages"`, your AMQP `exchange/routingKey` will receive all of the messages the configured `"authorizationContext": ["ditto:outbound-auth-subject", "..."]` is allowed to `READ` (based on the referenced policyId of the thing you sent the message to).

**Comment by peng9fei** [comment]
Thank you&nbsp; for your reply.


Now I use microk8s deployment a cloud2edge(eclipse hono, eclipse ditto) server on ubuntu&nbsp;virtual machine。


ubuntu:
Distributor ID: Ubuntu
Description:&nbsp; &nbsp; Ubuntu 20.04.6 LTS
Release:&nbsp; &nbsp; &nbsp; &nbsp; 20.04
Codename:&nbsp; &nbsp; &nbsp; &nbsp;focal
IP:192.168.74.128


cloud2edge:
microk8s.kubectl get services -n cloud2edge
NAME&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;TYPE&nbsp; &nbsp; &nbsp; &nbsp; CLUSTER-IP&nbsp; &nbsp; &nbsp; &nbsp;EXTERNAL-IP&nbsp; &nbsp;PORT(S)&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; AGE
c2e-ditto-dittoui&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ClusterIP&nbsp; &nbsp;10.152.183.19&nbsp; &nbsp; <none&gt;&nbsp; &nbsp; &nbsp; &nbsp; 8080/TCP&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;12h
c2e-ditto-gateway&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ClusterIP&nbsp; &nbsp;10.152.183.154&nbsp; &nbsp;<none&gt;&nbsp; &nbsp; &nbsp; &nbsp; 8080/TCP&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;12h
c2e-ditto-nginx&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; NodePort&nbsp; &nbsp; 10.152.183.156&nbsp; &nbsp;<none&gt;&nbsp; &nbsp; &nbsp; &nbsp; 8080:30973/TCP&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;12h
c2e-ditto-swaggerui&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ClusterIP&nbsp; &nbsp;10.152.183.98&nbsp; &nbsp; <none&gt;&nbsp; &nbsp; &nbsp; &nbsp; 8080/TCP&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;12h
c2e-hono-adapter-amqp&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; NodePort&nbsp; &nbsp; 10.152.183.228&nbsp; &nbsp;<none&gt;&nbsp; &nbsp; &nbsp; &nbsp; 5671:32671/TCP&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;12h
c2e-hono-adapter-http&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; NodePort&nbsp; &nbsp; 10.152.183.110&nbsp; &nbsp;<none&gt;&nbsp; &nbsp; &nbsp; &nbsp; 8443:30443/TCP&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;12h
c2e-hono-adapter-mqtt&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; NodePort&nbsp; &nbsp; 10.152.183.218&nbsp; &nbsp;<none&gt;&nbsp; &nbsp; &nbsp; &nbsp; 8883:30883/TCP&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;12h
c2e-hono-service-auth&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ClusterIP&nbsp; &nbsp;10.152.183.105&nbsp; &nbsp;<none&gt;&nbsp; &nbsp; &nbsp; &nbsp; 5671/TCP,8088/TCP&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 12h
c2e-hono-service-command-router&nbsp; &nbsp; &nbsp; &nbsp; ClusterIP&nbsp; &nbsp;10.152.183.53&nbsp; &nbsp; <none&gt;&nbsp; &nbsp; &nbsp; &nbsp; 5671/TCP&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;12h
c2e-hono-service-device-registry&nbsp; &nbsp; &nbsp; &nbsp;ClusterIP&nbsp; &nbsp;10.152.183.160&nbsp; &nbsp;<none&gt;&nbsp; &nbsp; &nbsp; &nbsp; 5671/TCP,8080/TCP,8443/TCP&nbsp; &nbsp;12h
c2e-hono-service-device-registry-ext&nbsp; &nbsp;NodePort&nbsp; &nbsp; 10.152.183.96&nbsp; &nbsp; <none&gt;&nbsp; &nbsp; &nbsp; &nbsp; 28443:31443/TCP&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 12h
c2e-kafka&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ClusterIP&nbsp; &nbsp;10.152.183.161&nbsp; &nbsp;<none&gt;&nbsp; &nbsp; &nbsp; &nbsp; 9092/TCP,9095/TCP&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 12h
c2e-kafka-controller-0-external&nbsp; &nbsp; &nbsp; &nbsp; NodePort&nbsp; &nbsp; 10.152.183.75&nbsp; &nbsp; <none&gt;&nbsp; &nbsp; &nbsp; &nbsp; 9094:30946/TCP&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;12h
c2e-kafka-controller-headless&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ClusterIP&nbsp; &nbsp;None&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<none&gt;&nbsp; &nbsp; &nbsp; &nbsp; 9094/TCP,9092/TCP,9093/TCP&nbsp; &nbsp;12h
c2e-mongodb&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ClusterIP&nbsp; &nbsp;10.152.183.170&nbsp; &nbsp;<none&gt;&nbsp; &nbsp; &nbsp; &nbsp; 27017/TCP&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 12h



run&nbsp;setCloud2EdgeEnv.sh and output:
export REGISTRY_IP="192.168.74.128"
export REGISTRY_PORT_HTTPS="31443"
export REGISTRY_BASE_URL="https://192.168.74.128:31443"
export AMQP_ADAPTER_IP="192.168.74.128"
export AMQP_ADAPTER_PORT_AMQPS="32671"
export HTTP_ADAPTER_IP="192.168.74.128"
export HTTP_ADAPTER_PORT_HTTPS="30443"
export HTTP_ADAPTER_BASE_URL="https://192.168.74.128:30443"
export MQTT_ADAPTER_IP="192.168.74.128"
export MQTT_ADAPTER_PORT_MQTTS="30883"
export DITTO_API_IP="192.168.74.128"
export DITTO_API_PORT_HTTP="30973"
export DITTO_API_BASE_URL="http://192.168.74.128:30973"
export DITTO_DEVOPS_PWD="IkbqoWQdXHam"
export DITTO_UI_ENV_JSON="{\"api_uri\":\"http://192.168.74.128:30973\",\"defaultUsernamePassword\":\"ditto:ditto\",\"defaultDittoPreAuthenticatedUsername\":null,\"defaultUsernamePasswordDevOps\":\"devops:IkbqoWQdXHam\",\"mainAuth\":\"basic\",\"devopsAuth\":\"basic\"}



Use docker deployment a RabbitMQ,
Use the ip:192.168.74.128 port:5672 username:guest password:guest I can visit RabbitMQ.


But I don't know how to configure the (eclipse ditto) connection or service to connect the RabbitMQ.



lbx
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eclipse-ditto/ditto"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月3日(星期一) 晚上6:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [eclipse-ditto/ditto] how to use ditto-client send message to RabbitMQ (java) (Issue #1949)





 
Sending messages can e.g. be done via the HTTP API:
 https://eclipse.dev/ditto/http-api-doc.html#/Messages/post_api_2_things__thingId__inbox_messages__messageSubject_
 
If you configured your connection for "target" "topic" "_/_/things/live/messages", your AMQP exchange/routingKey will receive all of the messages the configured "authorizationContext": ["ditto:outbound-auth-subject", "..."] is allowed to READ (based on the referenced policyId of the thing you sent the message to).

**Comment by thjaeckle** [comment]
If your problem still exists, please provide some properly formatted and formulated issue.

**Comment by peng9fei** [comment]
Thank you ,I have resolved the problem&nbsp; connect to RabbitMQ.
now I have another problem:I create some Things in Ditto, and a collection program send data to Ditto，to change Thing.Features .
{
&nbsp; &nbsp; &nbsp; "thingId": "nms:10",
&nbsp; &nbsp; &nbsp; "policyId": "nms:resources_policy",
&nbsp; &nbsp; &nbsp; "attributes": {
&nbsp; &nbsp; &nbsp; &nbsp; "inroutegroupname": "group1",
&nbsp; &nbsp; &nbsp; &nbsp; "MeshEnabled": 0
&nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; "features": {
&nbsp; &nbsp; &nbsp; &nbsp; "snmpdata": {
			"nmwarnings": "Failed",
			"nmalarms": "no alarm"
		},
&nbsp; &nbsp; &nbsp; &nbsp; "alarms": {}
&nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; }
now I create a java-client to listen the features/snmpdata/nmwarnings.
when the 'nmwarnings' equals some values，will&nbsp;trigger some handler.


client.twin().startConsumption(Options.Consumption.namespaces(namespace),
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 				Options.Consumption.filter("like(features/snmpdata/nmwarnings,'Alerm1')"))
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 		.toCompletableFuture().get(10, TimeUnit.SECONDS);



when I start the program,I got some exception:org.eclipse.ditto.base.model.exceptions.InvalidRqlExpressionException: Unknown property name: features/snmpdata/nmwarnings


lbx
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eclipse-ditto/ditto"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月25日(星期二) 晚上10:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [eclipse-ditto/ditto] how to use ditto-client send message to RabbitMQ (java) (Issue #1949)





 
If your problem still exists, please provide some properly formatted and formulated issue.

**Comment by thjaeckle** [comment]
Please don't answer via e-mail .. and please properly format your code - I cannot read anything.
