### ISSUE TITLE
how to scale connectivity instance

### ISSUE THREAD

**Issue by Lcq2002** [eclipse-ditto/ditto#1950]
I'm trying more modifies/s of connectivity . I find that I need to scale the connectivity instance, but I don't know how to scale it. Can I change the configuration in docker-compose to enable scaling or do I have to configure it in Kubernetes.
[https://eclipse.dev/ditto/2023-10-09-ditto-benchmark.html](url)
![image](https://github.com/eclipse-ditto/ditto/assets/56182562/bb026f44-67ec-41e3-83f7-1d2dac6fcaa7)

**Comment by thjaeckle** [comment]
@Lcq2002 if you run Ditto in Kubernetes, then scale the `ditto-connectivity` deployment via Kubernetes: https://kubernetes.io/docs/reference/kubectl/generated/kubectl_scale/

Or - if deployed with the Ditto Helm chart - configure it:
https://github.com/eclipse-ditto/ditto/blob/fe3c928e6f5c29231e06ac259c4180842a682028/deployment/helm/ditto/values.yaml#L1133-L1137

If you run Ditto via Docker-Compose (which however would be only locally on a single machine), scale it via Docker-Compose `replicas`: https://docs.docker.com/compose/compose-file/deploy/#replicas

**Comment by Lcq2002** [comment]
@thjaeckle Thank you very much for your reply. I have successfully expanded the number of connectivity to 5 in docker-compose and modified the clientCount to equal the number of connectivity instances, but my modifies/s of connectivity have not increased significantly, is this due to the Is this because of the docker deployment? Do I have to use Kubernetes for the expansion to work?

**Comment by thjaeckle** [comment]
The limiting factor could be the machine or the docker-compose configuration, which is not really suited for productive purposes.
For productive scenarios where scaling is required, I would always recommend the k8s based deployment based on the Ditto Helm chart - and to fine-tune the parameters (cpu and memory `resources` and e.g. `activeProcessorCount`,  `heapRamPercentage`) according to your use-case based on the JVM-tuning experience of a good DevOps.

**Comment by Lcq2002** [comment]
@thjaeckle  Thank you for your suggestions and detailed explanation! We will consider using the k8s-based deployment. Your guidance is greatly appreciated!
