### ISSUE TITLE
How to send specific headers when using hono-ditto kafka connector and map headers when using MQTT - adapter at device end

### ISSUE THREAD

**Issue by srinivaschannakeshava** [eclipse-ditto/ditto#1970]
Trying to map device events to update connection status and receiving this error at ditto consumption -

`2024-06-21 11:52:56 2024-06-21 06:22:56,976 INFO  [][] o.e.d.c.s.m.ConnectionStatusMessageMapper  - Error occurred during mapping: <MessageMappingFailedException>: Header <ttd> is not set.`

1. Also is there a way to enable connection and disconnection events to be published on kafka from MQTT adapter in Hono?
2. If there needs to be custom headers that needs to be added on the kafka published message - how can this be enabled when using mqtt-adapter ?

**Comment by thjaeckle** [comment]
Apparently noone knew an answer. 
Did you solve this?
