### ISSUE TITLE
The procedure to use https url of the definition for creating thing

### ISSUE THREAD

**Issue by Korakbhakta02** [eclipse-ditto/ditto#1976]
Hi,
I have exposed a definition url through WSO2 gateway as HTTPS url. It doesnot have authentication. When I try to create a thing with this HTTPS definition link, it is giving me error: "Please ensure that the linked ThingModel is publicly available in order to be downloaded."

Is there any way to make ditto use the HTTPS secured definition url to create thing?

**Comment by thjaeckle** [comment]
Hi.
I don't know what a WSO2 gateway is, but Ditto just needs to be able to download the TM referenced in a definition via this Http endpoint.
So this might even be a cluster internal endpoint, as long as Ditto is able to download via the cluster internal Http endpoint
. 
If it is a Https endpoint and has a valid, publicly trusted, certificate, Ditto will be able to download it (if no network rules prevent that Ditto calls outside URLs). 
If eg the certificate is self signed, you need to configure the certificate in the Java truststore, as you would for every JVM application.

**Comment by Korakbhakta02** [comment]
is it possible to manage the truststore in backend of ditto?

**Comment by thjaeckle** [comment]
@Korakbhakta02 sure, like I mentioned above:
> If eg the certificate is self signed, you need to configure the certificate in the Java truststore, as you would for every JVM application.

So e.g. mounting a custom truststore as Docker volume and adjusting the according system property to point to that location, see e.g.:
https://medium.com/@vishwanath.leo/how-to-pass-your-custom-truststore-as-argument-to-jvm-when-running-a-jar-file-f9e05adc5094

Or you could create a custom Docker image, where you add the custom truststore to the custom Docker image (in which you reference the `ditto-things` image - which does the downloading of the WoT model).

**Comment by Korakbhakta02** [comment]
Thanks, I am now able to create thing with HTTPS definition.
