### ISSUE TITLE
Unable to authorize ditto installed via docker compose

### ISSUE THREAD

**Issue by dheeru0802** [eclipse-ditto/ditto#1978]
I have been working on a project related to digital twins, and we are trying to implement Eclipse Ditto for our use case.
We use sensor nodes with MQTT connections in the implementation stage at the edge. We are facing issues when we are deploying Eclipse ditto. We have deployed ditto on WSL working on a Windows 11 system. We are using Docker Compose with Nginx for reverse proxy and basic authentication for Eclipse Ditto.

The app deploys correctly on localhost:8080. When we try to authorise Ditto UI using a username and password, I keep encountering a 404 error despite following troubleshooting steps like verifying URLs, checking Nginx configuration, inspecting Ditto logs, and restarting services. We have also tried using the Ubuntu virtual machine, but the issue persists.

We have done the following troubleshooting steps to resolve this issue:
Checked ports on docker-compose.yaml file.
Checked nginx.conf and other configuration files.
Created nginx.htpasswd file and added a new user in format ditto:{open SSL password hash}

We keep getting the 404 error when trying to authenticate Eclipse ditto. when im trying the curl command to create a policy i get 405 error We searched everywhere for the solution, but the steps were identical to those we had performed.

**Comment by thjaeckle** [comment]
Hi @dheeru0802 

> We keep getting the 404 error when trying to authenticate Eclipse ditto. 

What response do you get with that 404?
A JSON response from Ditto? Which one if yes?
What do the log files log, e.g. of the `gateway` service?

 Please share some more details.
