### ISSUE TITLE
error pulling image configuration: download failed after attempts=6: 

### ISSUE THREAD

**Issue by antoniojiawen** [eclipse-ditto/ditto#1980]
when I use "docker-compose up -d" or "docker pull eclipse/ditto-policies" only project "eclipse", It cause
 "error pulling image configuration: download failed after attempts=6: dialing production.cloudflare.docker.com:443 container via direct connection because static system has no HTTPS proxy: connecting to 31.13.106.4:443: dial tcp 31.13.106.4:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."

**Comment by thjaeckle** [comment]
Ditto images are not hosted on `production.cloudflare.docker.com:443` - that is probably a Docker proxy in your infrastructure.
I would suggest to check if that setup can pull from Docker hub.
