### ISSUE TITLE
javax.annotation不 存在

### ISSUE THREAD

**Issue by antoniojiawen** [eclipse-ditto/ditto#1981]
when i use "mvn clean install -DskipTests" cause

 D:\workspace\java\dittospace\ditto-master\internal\utils\pekko\src\main\java\org\eclipse\ditto\internal\utils\pekko\PingCommand.java:18:23:  错误: 程序包javax.annotation不 存在

**Comment by thjaeckle** [comment]
That seems to be a local issue of your setup.
Builds on both Jenkins and GitHub actions pass.
