### ISSUE TITLE
Authorization Header used in internal service communication

### ISSUE THREAD

**Issue by pedro-nicolau-carvalho** [eclipse-ditto/ditto#1983]
Hello,

I have set up JWT authentication and authorization in Ditto, but I am getting a `DittoHeadersTooLargeException` in the gateway service when passing along my JWT token. It seems that when adding the subjects to the DittoHeaders, the gateway service overflows the maximum allowed length for the headers. Is this max configurable? It does not seem to be the same as `pekko.http.server.parsing.max-header-value-length`. 

I also noticed in the logs that the JWT token is being set in Ditto headers. Is there a way to skip some headers like this? I would assume that the JWT token is not needed for internal communication between the services since the subjects are already calculated in the gateway service, am I wrong?

Thank you.

**Comment by thjaeckle** [comment]
Hi @pedro-nicolau-carvalho 

How do you deploy Ditto?
The `Authorization` header should be excluded from the "header propagation" in the Ditto Helm chart:
https://github.com/eclipse-ditto/ditto/blob/8f48e9622ae7fb2de77905e08cc3c88a830fef81/deployment/helm/ditto/values.yaml#L1507

So there is a way to skip a list of defined headers (by configuration) from being propagated.
I would check which ones cause a lot of payload and exclude them, if not needed, same as the Helm chart config already does:
https://github.com/eclipse-ditto/ditto/blob/8f48e9622ae7fb2de77905e08cc3c88a830fef81/deployment/helm/ditto/values.yaml#L1495-L1515

If you add a lot of subjects from the JWT as `authSubjects` to the DittoHeaders, the headers could also get too large.
There is also a configuration of a max. amount of auth subjects - if this is exceeded, the same exception is also thrown:
https://github.com/eclipse-ditto/ditto/blob/8f48e9622ae7fb2de77905e08cc3c88a830fef81/edge/service/src/main/resources/ditto-edge-service.conf#L27-L29

You can also increase the max. possible size of the headers, which is by default 5k:
https://github.com/eclipse-ditto/ditto/blob/8f48e9622ae7fb2de77905e08cc3c88a830fef81/edge/service/src/main/resources/ditto-edge-service.conf#L23-L25

**Comment by pedro-nicolau-carvalho** [comment]
Hello @thjaeckle,

I am using https://github.com/eclipse-ditto/ditto/blob/master/deployment/docker/sandbox/docker-compose.yml as a starting point, but from the way it was setup I understand now why it was not blocking those headers (I removed the nginx and added JWT integration which caused the problem).

Thank you!
