### ISSUE TITLE
Complex JWT placeholder subject mapping - Keycloak RPT integration

### ISSUE THREAD

**Issue by pedro-nicolau-carvalho** [eclipse-ditto/ditto#1984]
Hello,

I am currently integrating Keycloak with Eclipse Ditto. Since granting user permissions is done elsewhere from ditto, my idea is to map specific resources and scopes as subjects in Ditto and use a user's RPT token as the input of this mapping. The RPT token, granted by keycloak, is a JWT token that contains some user's permissions. The structure is as follows: 

```
{
  "authorization": {
      "permissions": [
        {
          "scopes": [ "device.read" ],
          "resource_set_id": "d2fe9843-6462-4bfc-baba-b5787bb6e0e7",
          "resource_set_name": "Device 1"
        },
        {
          "scopes": [ "device.read", "device.write" ],
          "resource_set_id": "d2fe9843-6462-4bfc-baba-b5787bb6e0e7",
          "resource_set_name": "Device 12
        }
      ]
  },
  "jti": "d6109a09-78fd-4998-bf89-95730dfd0892-1464906679405",
  "exp": 1464906971,
  "nbf": 0,
  "iat": 1464906671,
  "sub": "f1888f4d-5172-4359-be0c-af338505d86c",
  "typ": "kc_ett",
  "azp": "hello-world-authz-service"
}
```

my idea is to then, from this RPT, generate subjects:
- `d2fe9843-6462-4bfc-baba-b5787bb6e0e7#device.read`
- `d2fe9843-6462-4bfc-baba-b5787bb6e0e7#device.read`
- `d2fe9843-6462-4bfc-baba-b5787bb6e0e7#device.write`. 
With these subjects, a policy for a thing would include these subjects in the appropriate place (e.g. subject `d2fe9843-6462-4bfc-baba-b5787bb6e0e7#device.read` would be granted permission to read thing d2fe9843-6462-4bfc-baba-b5787bb6e0e7).

I have tried using jwt placeholders to convert the JWT token to the format I require, but I am not sure if it is possible. It seems that the supported json operations are very limited. For example, using the token structure above:
- JSON pointer indexing does not work (example: `authorization/permissions/0`)
- Can't do operations in nested objects. To reach something like `resource_set_id#scope`, I would have to do something like `{{ jwt:authorization/permissions | join(resource_set_id, scopes, '#') }}` (`join` function is merely ilustrative). The issue here is everything to the output of `jwt:claim` is acted on as a string and not as objects themselves.

Am I correct in assuming that the mapping I want is not currently possible using placeholders?

Thank you.

**Comment by thjaeckle** [comment]
Hi @pedro-nicolau-carvalho 

The JWT placeholder is quite mighty:
https://eclipse.dev/ditto/basic-placeholders.html#scope-openid-connect-configuration

It e.g. has a special handling for JSON arrays (and even JSON objects in arrays) - iterating over all entries and "multiplying" the result.

However, it seems we did not consider yet the "array in array" use case.
It also seems that only arrays in "root level" are currently supported .. I would say this is a bug, that should work also in nested structures.
I will create a ticket for that and can provide a fix.

What you however want to achieve is not yet supported, I fear .. selecting and combining fields only "on the same level".
But that is a very valid and useful use case. 👍 
We could track that as new issue.

**Comment by pedro-nicolau-carvalho** [comment]
> It e.g. has a special handling for JSON arrays (and even JSON objects in arrays) - iterating over all entries and "multiplying" the result.

Is it currently possible to extract a property from a nested JSON object in an array without parsing the JSON object as a string? For example, using the structure from the RPT, is it possible to extract the `resource_set_id`as the authorization subjects? I have tried using `{{ jwt:authorization/permissions/resource_set_id }}` and `{{ jwt:authorization/permissions/0/resource_set_id }}` but without luck

**Comment by thjaeckle** [comment]
As mentioned: It should be possible .. however it currently only seems to work if the array is directly at the "first level" of the JSON, see created bug issue #1985 

> For example, using the structure from the RPT, is it possible to extract the resource_set_idas the authorization subjects? I have tried using `{{ jwt:authorization/permissions/resource_set_id }}` and `{{ jwt:authorization/permissions/0/resource_set_id }}` but without luck
Yes, that unfortunately is affected by the bug :/ 

`{{ jwt:authorization/permissions/resource_set_id }}` should work that way ..
Using the array-index is not supported ..

**Comment by thjaeckle** [comment]
With the recently released Ditto 3.6.0 the Bugfix regarding JWT claim parsing in arrays of objects was resolved.

Closing this question..

**Comment by malavikaiplon** [comment]
Hi @thjaeckle 
/api/2/whoami this giving below results {
  "defaultSubject": "nginx:",
  "subjects": [
    "nginx:"
  ]
} i also have doubt like why does the gateway service log not giving any connection logs of my OIDC issuer (keycloak) after i configure it in gateway.conf , i not sure where i am missing

**Comment by thjaeckle** [comment]
You seem to still have `pre-authentication` (https://eclipse.dev/ditto/installation-operating.html#pre-authentication) enabled - but your nginx does not authenticate a user.

**Comment by malavikaiplon** [comment]
Hi @thjaeckle ,

**Comment by thjaeckle** [comment]
Please share how you apply your configuation.
As a mount in the container?
As environment variables?

**Comment by malavikaiplon** [comment]
hi @thjaeckle ,

here is my docker-compose.yaml gateway service configuration  
gateway:
    image: docker.io/eclipse/ditto-gateway:${DITTO_VERSION:-latest}
    mem_limit: 512m
    restart: always
    networks:
      default:
        aliases:
          - ditto-cluster
    depends_on:
      - policies
    ports:
      - "8081:8080"
    environment:
      - TZ=Europe/Berlin
      - INSTANCE_INDEX=1
      - BIND_HOSTNAME=0.0.0.0
      - ENABLE_PRE_AUTHENTICATION=false
      - ENABLE_DUMMY_AUTH=true
      - OPENJ9_JAVA_OPTIONS=-XX:+ExitOnOutOfMemoryError -Xtune:virtualized -Xss512k -XX:MaxRAMPercentage=80 -Dakka.coordinated-shutdown.exit-jvm=on -Dakka.cluster.shutdown-after-unsuccessful-join-seed-nodes=120s
    command: java -Dditto.gateway.authentication.devops.password=foobar -Dditto.gateway.authentication.oauth.protocol=http -Dditto.gateway.authentication.oauth.openid-connect-issuers.keycloak=keycloak-test.test.co.in/auth/realms/master -jar starter.jar

i followed this https://github.com/eclipse-ditto/ditto/issues/876 but i couldn't up the gateway services with this configuration. it keep restarting gateway service and getting this error from gateway log 
Error: Unable to access jarfile starter.jar
Error: Unable to access jarfile starter.jar
Error: Unable to access jarfile starter.jar

**Comment by thjaeckle** [comment]
> `-Dditto.gateway.authentication.oauth.openid-connect-issuers.keycloak=keycloak-test.test.co.in/auth/realms/master`

This is wrong.
As [documented](https://eclipse.dev/ditto/installation-operating.html#openid-connect) this needs to be:
```
-Dditto.gateway.authentication.oauth.openid-connect-issuers.keycloak.issuer=keycloak-test.test.co.in/auth/realms/master
```

**Comment by malavikaiplon** [comment]
HI @thjaeckle ,

Thank you ,It's working now when i changed the configuration like this in docker-compose.yaml file gateway service environment  
environment:
      - TZ=Europe/Berlin
      - BIND_HOSTNAME=0.0.0.0
      - ENABLE_PRE_AUTHENTICATION=false
      - JAVA_TOOL_OPTIONS=-XX:ActiveProcessorCount=2 -XX:+ExitOnOutOfMemoryError -XX:+UseContainerSupport -XX:+UseStringDeduplication -Xss512k -XX:MaxRAMPercentage=50 -XX:+UseG1GC -XX:MaxGCPauseMillis=150 -Dpekko.coordinated-shutdown.exit-jvm=on -Dpekko.cluster.shutdown-after-unsuccessful-join-seed-nodes=180s -Dpekko.cluster.failure-detector.threshold=15.0 -Dpekko.cluster.failure-detector.expected-response-after=10s -Dpekko.cluster.failure-detector.acceptable-heartbeat-pause=20s -Dpekko.cluster.downing-provider-class= -Dditto.gateway.authentication.oauth.protocol=http -Dditto.gateway.authentication.oauth.openid-connect-issuers.keycloak.issuer=keycloak-test.test.co.in/auth/realms/master
