### ISSUE TITLE
Sort Operation for Things-Search API shows 400 Error

### ISSUE THREAD

**Issue by Subhaditya16** [eclipse-ditto/ditto#1988]
Hi,
I am trying to make a sort operation using the Things-Search API:
so when I try to call this - **api/2/search/things?option=sort(+thingId)**

It is throwing an error: 
{
    "status": 400,
    "error": "rql.expression.invalid",
    "message": "Invalid input ' ', expected Asc or Desc (line 1, column 6):\nsort( thingId)\n     ^",
    "description": "Ensure that all opening parentheses have also closing ones and that the RQL expression is valid."
}

However when I replace the + with a - , it works as expected

**Comment by thjaeckle** [comment]
Hi @Subhaditya16 

You'll have to URL encode the `+` in that case .. `+` is otherwise substituted with a space.
See also: https://stackoverflow.com/questions/5450190/how-to-encode-the-plus-symbol-in-a-url
