### ISSUE TITLE
patch kind of update in Kafka connection(source) without removing the existing values

### ISSUE THREAD

**Issue by kulta4** [eclipse-ditto/ditto#1993]
Hi there!
         I tried to update the twin using Kafka connection (source), to add/delete the specific values without removing the existing values. but not able to update/delete as I expected.
         this is the twin structure I tried to Update:
   {
  "thingId": "the.namespace:the-thing-id",
  "policyId": "the.namespace:the-policy-id",
  "features": {
    "fruits": [
      "oranges",
      "bananas",
      "grapes",
      "strawberries"
    ]
  }
}
              I want to update the fruits value without removing the existing values as I mentioned above.
              This is the payload I used to update:
 {"topic":"<namespace>/<thingId>/things/twin/commands/merge","headers": {"content-type": "application/merge-patch+json"},"path":"/features/fruits","value": ["apples","kiwis", "lemons", "avocados"]}    --->   this will replace with the existing values , but i want to add the values. for delete also I didn't find any way to delete specific fruit name alone, not all the names. Please suggest the way to update/delete a feature if the Key-values are in array format.
 
 Thank you.

**Comment by pedro-nicolau-carvalho** [comment]
Hello,

I'm not a contributor of Ditto, but the [documentation](https://eclipse.dev/ditto/2021-02-04-merge-feature.html) states that the merge functionality uses the[ JSON Merge Patch](https://datatracker.ietf.org/doc/html/rfc7396) semantics, which do not allow for updates to arrays (the value is always replaced).

>   (...)  If the patch is
   anything other than an object, the result will always be to replace
   the entire target with the entire patch.  Also, it is not possible to
   patch part of a target that is not an object, such as to replace just
   some of the values in an array.
