### ISSUE TITLE
Unstability of Ditto AFter creating large number of Things

### ISSUE THREAD

**Issue by Korakbhakta02** [eclipse-ditto/ditto#2008]
Hi, We have eclipse ditto installed in an AWSmachine. There, we were creating small amount of things like 400 to 500 things. But, when we inserted approx 20000 things, ditto became unstable . That means it sometime gives response, after that, it gives blank response or time out error while fetching things. How can we solve that?

**Comment by thjaeckle** [comment]
Please share some details..

How did you setup and scale Ditto?
How many instances for the services, how much memory and CPU per instance?

**Comment by thjaeckle** [comment]
Yeah, ok .. then no wonder it crashes - please scale it appropriately both vertically and horizontally.
Here you can get an idea of what was needed in order to scale to 1.000.000 things:
https://eclipse.dev/ditto/2023-10-09-ditto-benchmark.html
