### ISSUE TITLE
Eclipse Ditto and BaSyx Integration

### ISSUE THREAD

**Issue by charanhs123** [eclipse-ditto/ditto#2016]
Hello,
The Blog post explaining Ditto and BaSyx integration is no longer working, Please update the post or add a new one to the blog

thank you

**Comment by charanhs123** [comment]
Hello , Thanks for the quick reply
I am attaching the screen shot below of issue , the Steps you have provided doesn't actually seems to work like depicted in the blog, and the aasGui is not working like shown in the Blog example

![Screenshot from 2024-09-09 16-32-41](https://github.com/user-attachments/assets/1f923f39-43fd-4bc5-9361-bad327a32812)
![Screenshot from 2024-09-09 16-32-30](https://github.com/user-attachments/assets/993adc56-e414-4d68-9dea-505906d44070)

**Comment by thjaeckle** [comment]
Ah, I understood that the page cannot be loaded.
I do not have interest in keeping that one-time example working all the time.

Maybe you can reach out to the authors of the post @bs-jokri and @eriksven to get some help.

**Comment by charanhs123** [comment]
hello @bs-jokri and @eriksven I hope you are interested in replying

**Comment by eriksven** [comment]
Hello @charanhs123 ,
It is great that you show interest in reproducing the blog post. To be sure, are you talking about the post from: https://eclipse.dev/ditto/2024-02-27-integrating-ditto-aas-basyx.html ? 
As mentioned by @thjaeckle the nature of the blog post was to demonstrate what was possible at the time of writing. There is a chance that using a more recent version of any of the involved components might lead to breaking changes.
Which versions did you use for the involved components?

Could you please elaborate on what you did to get to the situation from the screenshots?
What do you want to achieve at the end of the day?

In your screenshot, it says that the status of the connection with the AAS registry is "offline". So it appears that there is either:

- a problem with the connectivity between the AAS Web UI and the AAS registry and AAS server
- a problem with the deployment of the AAS registry and AAS server

Can you make direct HTTP calls to the AAS registry or AAS server, e.g., through cURL, Swagger, etc., from the same machine from which you call the AAS WebUI?
In the blog post, there are some examples of how to interact with the AAS server and registry. Using and setting up the AAS Web-UI is more an addition to showing how the integration between Ditto and AAS worked. In case of more detailed questions about the AAS WebUI, it is better to get in contact with those developers.

**Comment by charanhs123** [comment]
Hello @eriksven thanks for the reply
So, I wanted to present an Interface in Master Thesis for the Eclipse Ditto using BaSyx, so I worked your examples to implement the tree view of the Thing we create in Ditto but even with the default example in the Blog Post I was not able to reproduce like what s been shown.

i am able to access and change the features and other points from the terminal and able to view in json format when looked in browser under 
http://192.168.10.15:8082/aasServer/shells/ and for registry aswell, but like I have shown in the screen shot its showing "Status: Offline" and I am bale to get the Tree view .

The deployment of AAS registry and Server is proper there s no issue with that , but I am not able to view the submodels and the elements on GUI.

**Comment by max-grzanna** [comment]
Hello @charanhs123,
to better understand your problem, it would be helpful if you could list the versions of the components you are using. You seem to be using a newer version of WebUI. This can lead to conflicts and the endpoints may have changed. 
Were you able to find any anomalies in the logs of the components?

**Comment by charanhs123** [comment]
hello @max-grzanna i am using v - 230703 
i am attaching my Docker-compose.yml i am using 

`
version: '3.8'

services:
  aasRegistry:
    image: eclipsebasyx/aas-registry:1.5.1
    container_name: aasRegistry
    ports:
      - "8083:4000"
    networks:
      - basyx-network

  aasServer:
    image: eclipsebasyx/aas-server:1.5.1
    container_name: aasServer
    ports:
      - "8082:4001"
    networks:
      - basyx-network

  aasGui:
    image: eclipsebasyx/aas-gui:v230703
    container_name: aasGui
    ports:
      - "5000:3000"
    networks:
      - basyx-network

networks:
  basyx-network:
    driver: bridge
`

**Comment by thjaeckle** [comment]
Closing, not Ditto related, but Basyx
