### ISSUE TITLE
Configure workflow for running system tests

### ISSUE THREAD

**Issue by alstanchev** [eclipse-ditto/ditto#2029]
It is goot to run the system tests from ditto-testing repo against PRs and master branch.
Running from PRs should be manual after a review from a maintainer that running is safe.

**Comment by alstanchev** [comment]
@thjaeckle i am almost ready with that. Any input for the ways we want to be able to run the tests is welcome. Currently i am going in the direction of manual run with providing the pranch/PR as input.

**Comment by thjaeckle** [comment]
@alstanchev awesome, that sounds great :)

> Currently i am going in the direction of manual run with providing the pranch/PR as input.

I think this is perfect as first step.

Looking much forward to this 👍
