### ISSUE TITLE
digital twin tutorial

### ISSUE THREAD

**Issue by mfatihkoc** [eclipse-ditto/ditto#2030]
there is a testbed RAN is composed of a Base Station and multiple UEs, all deployed as USRPs. the dataset is containing network performance features with benign and malicious attacks where 4G mobility pattern is included (car, padestrian). I want to use ditto as a digital twin framework but I could not start. is there any tutorial for networking aspects directed to vehicular communication?

**Comment by thjaeckle** [comment]
> is there any tutorial for networking aspects directed to vehicular communication?

No, there is no such thing.
