### ISSUE TITLE
Migrating old version ditto's data to new version ditto

### ISSUE THREAD

**Issue by Korakbhakta02** [eclipse-ditto/ditto#2065]
I was using ditto 3.2.1 earlier and it was storing data in a external mongodb. Now, I upgraded ditto to 3.6.2. The database I kept same. I am able to get the things. But when creating thing, I am getting error:
``
MongoCommandException: Command failed with error 85 (IndexOptionsConflict): 'Index already exists with a different name: akka_persistence_metadata_pid' on server <mongoip>:27017. The full response is {\"ok\": 0.0, \"errmsg\": \"Index already exists with a different name: akka_persistence_metadata_pid\", \"code\": 85, \"codeName\": \"IndexOptionsConflict\"}\n\tat
``
when I checked the database, index name is 'akka_persistence_metadata_pid' and for the latest ditto, index name is things_metadata_index for which the conflict is happening. SO,I want to know if  any other such conflicts will happen or not?And how to migrate the data from old ditto to latest ditto?

**Comment by alstanchev** [comment]
https://eclipse.dev/ditto/release_notes_340.html#swapping-the-akka-toolkit-with-its-fork-apache-pekko
https://eclipse.dev/ditto/release_notes_340.html#migration-notes
